// This file was autogenerated by ./libraries/closure-library-20120710-r2029/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../app.js', ['panoptikos.Panoptikos'], ['goog.dom', 'goog.events', 'panoptikos.config.core', 'panoptikos.ui.Board', 'panoptikos.ui.BoardControls', 'panoptikos.ui.SubredditPicker', 'panoptikos.ui.SubredditPickerLauncher']);
goog.addDependency('../../config/core.js', ['panoptikos.config.core'], []);
goog.addDependency('../../models/subreddit.js', ['panoptikos.models.subreddit'], []);
goog.addDependency('../../ui/board-controls.js', ['panoptikos.ui.BoardControls', 'panoptikos.ui.BoardControls.EventType'], ['goog.dom', 'goog.events', 'goog.events.Event', 'goog.events.EventTarget']);
goog.addDependency('../../ui/board-item.js', ['panoptikos.ui.BoardItem'], ['goog.dom']);
goog.addDependency('../../ui/board.js', ['panoptikos.ui.Board', 'panoptikos.ui.Board.EventType', 'panoptikos.ui.BoardEvent'], ['goog.Uri', 'goog.debug.Logger', 'goog.dom', 'goog.events.EventTarget', 'goog.net.Jsonp', 'goog.userAgent', 'panoptikos.models.subreddit', 'panoptikos.ui.BoardControls.EventType', 'panoptikos.ui.BoardItem']);
goog.addDependency('../../ui/subreddit-picker-launcher.js', ['panoptikos.ui.SubredditPickerLauncher'], ['goog.dom']);
goog.addDependency('../../ui/subreddit-picker.js', ['panoptikos.ui.SubredditPicker', 'panoptikos.ui.SubredditPicker.EventType'], ['goog.dom', 'goog.dom.classes', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventType', 'goog.events.KeyCodes', 'goog.style']);
