application: panoptikos3
version: 2013-03-13-0
runtime: go
api_version: go1

# Default expiration for static files
default_expiration: 5d

handlers:
# Any file ending with .css
- url: /(.*\.css)
  static_files: webroot/compiled-css/\1
  upload: webroot/compiled-css/.*\.css

# Any file ending with .js
- url: /(.*\.js)
  static_files: webroot/compiled-js/\1
  upload: webroot/compiled-js/.*\.js

# Special case: apple-touch-icon.png does not exist in our directory, but some
# browsers always ask for it.
- url: /apple-touch-icon\.png
  static_files: webroot/images/apple-touch-icon-iphone.png
  upload: webroot/images/apple-touch-icon-iphone\.png

# Special case: favicon.ico does not exist in our directory, but some browsers
# always ask for it.
- url: /favicon\.ico
  static_files: webroot/images/favicon-16.ico
  upload: webroot/images/favicon-16\.ico

# Any file ending with .gif, .ico, .jpg or .png
- url: /(.*\.(?:gif|ico|jpg|png))
  static_files: webroot/images/\1
  upload: webroot/images/.*\.(?:gif|ico|jpg|png)

- url: /dev-js/
  static_dir: webroot/dev-js/

- url: /robots\.txt
  static_files: webroot/robots.txt
  upload: webroot/robots\.txt
  expiration: 1h

- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?assetcompiler
- ^(.*/)?libraries/closure-compiler-20120917-r2180
- ^(.*/)?libraries/closure-library-20120710-r2029
- ^(.*/)?libraries/closure-stylesheets-20111230
- ^(.*/)?webroot/dev-css
- ^(.*/)?webroot/dev-js
