application: panoptikos3
version: 2013-03-10-7
runtime: go
api_version: go1

handlers:
- url: /css/
  static_dir: webroot/compiled-css/

- url: /dev-css/
  static_dir: webroot/dev-css/

- url: /dev-js/
  static_dir: webroot/dev-js/

- url: /favicon\.ico
  static_files: webroot/images/favicon-16.ico
  upload: webroot/images/favicon-16.ico

- url: /images/
  static_dir: webroot/images/

- url: /js/
  static_dir: webroot/compiled-js/

- url: /robots\.txt
  static_files: webroot/robots.txt
  upload: webroot/robots.txt

- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?assetcompiler
- ^(.*/)?libraries/closure-compiler-20120917-r2180
- ^(.*/)?libraries/closure-library-20120710-r2029
- ^(.*/)?libraries/closure-stylesheets-20111230
- ^(.*/)?webroot/dev-css
- ^(.*/)?webroot/dev-js
