var h=void 0,i=!0,j=null,l=!1,r,t=this;function aa(a){for(var a=a.split("."),b=t,c;c=a.shift();)if(b[c]!=j)b=b[c];else return j;return b}function u(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function v(a){return"array"==ba(a)}function da(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function w(a){return"string"==typeof a}function ea(a){return"function"==ba(a)}function fa(a){var b=typeof a;return"object"==b&&a!=j||"function"==b}function ga(a){return a[ha]||(a[ha]=++ia)}var ha="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ia=0;
function ja(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return x.apply(j,arguments)}var la=Date.now||function(){return+new Date};
function y(a,b){function c(){}c.prototype=b.prototype;a.jb=b.prototype;a.prototype=new c};function ma(a,b){for(var c=1;c<arguments.length;c++)var d=String(arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,d);return a}function z(a){if(!na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(pa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(qa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ra,"&quot;"));return a}var oa=/&/g,pa=/</g,qa=/>/g,ra=/\"/g,na=/[&<>\"]/;var A,sa,ta,ua;function va(){return t.navigator?t.navigator.userAgent:j}ua=ta=sa=A=l;var wa;if(wa=va()){var xa=t.navigator;A=0==wa.indexOf("Opera");sa=!A&&-1!=wa.indexOf("MSIE");ta=!A&&-1!=wa.indexOf("WebKit");ua=!A&&!ta&&"Gecko"==xa.product}var ya=A,B=sa,C=ua,D=ta,za=t.navigator,Aa=-1!=(za&&za.platform||"").indexOf("Mac"),Ba;
a:{var Ca="",E;if(ya&&t.opera)var Da=t.opera.version,Ca="function"==typeof Da?Da():Da;else if(C?E=/rv\:([^\);]+)(\)|;)/:B?E=/MSIE\s+([^\);]+)(\)|;)/:D&&(E=/WebKit\/(\S+)/),E)var Ea=E.exec(va()),Ca=Ea?Ea[1]:"";if(B){var Fa,Ga=t.document;Fa=Ga?Ga.documentMode:h;if(Fa>parseFloat(Ca)){Ba=String(Fa);break a}}Ba=Ca}var Ha={};
function G(a){var b;if(!(b=Ha[a])){b=0;for(var c=String(Ba).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",k=d[e]||"",s=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var q=s.exec(g)||["","",""],m=n.exec(k)||["","",""];if(0==q[0].length&&0==m[0].length)break;b=((0==q[1].length?0:parseInt(q[1],10))<(0==m[1].length?0:parseInt(m[1],10))?-1:(0==q[1].length?0:parseInt(q[1],
10))>(0==m[1].length?0:parseInt(m[1],10))?1:0)||((0==q[2].length)<(0==m[2].length)?-1:(0==q[2].length)>(0==m[2].length)?1:0)||(q[2]<m[2]?-1:q[2]>m[2]?1:0)}while(0==b)}b=Ha[a]=0<=b}return b}var Ia={};function Ja(){return Ia[9]||(Ia[9]=B&&!!document.documentMode&&9<=document.documentMode)};function Ka(){}var La=0;r=Ka.prototype;r.key=0;r.u=l;r.ea=l;r.P=function(a,b,c,d,f,e){if(ea(a))this.oa=i;else if(a&&a.handleEvent&&ea(a.handleEvent))this.oa=l;else throw Error("Invalid listener argument");this.I=a;this.ta=b;this.src=c;this.type=d;this.capture=!!f;this.Y=e;this.ea=l;this.key=++La;this.u=l};r.handleEvent=function(a){return this.oa?this.I.call(this.Y||this.src,a):this.I.handleEvent.call(this.I,a)};function Ma(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Na(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Pa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Oa.length;e++)c=Oa[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};!B||Ja();var Qa=!B||Ja(),Ra=B&&!G("8");!D||G("528");C&&G("1.9b")||B&&G("8")||ya&&G("9.5")||D&&G("528");C&&!G("8")||B&&G("9");function H(a){Error.captureStackTrace?Error.captureStackTrace(this,H):this.stack=Error().stack||"";a&&(this.message=String(a))}y(H,Error);H.prototype.name="CustomError";function Sa(a,b){b.unshift(a);H.call(this,ma.apply(j,b));b.shift();this.ub=a}y(Sa,H);Sa.prototype.name="AssertionError";function Ta(a,b){throw new Sa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var I=Array.prototype,J=I.indexOf?function(a,b,c){return I.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(w(a))return!w(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ua=I.forEach?function(a,b,c){I.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=w(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},Va=I.filter?function(a,b,c){return I.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,g=w(a)?a.split(""):
a,k=0;k<d;k++)if(k in g){var s=g[k];b.call(c,s,k,a)&&(f[e++]=s)}return f},Wa=I.some?function(a,b,c){return I.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=w(a)?a.split(""):a,e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return i;return l};function Xa(a,b){var c=J(a,b);0<=c&&I.splice.call(a,c,1)}function Ya(a){return I.concat.apply(I,arguments)}function Za(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function $a(a,b,c){return 2>=arguments.length?I.slice.call(a,b):I.slice.call(a,b,c)};function ab(){this.Ha=l};function K(a,b){this.type=a;this.currentTarget=this.target=b}K.prototype.t=l;K.prototype.defaultPrevented=l;K.prototype.U=i;K.prototype.preventDefault=function(){this.defaultPrevented=i;this.U=l};function bb(a){bb[" "](a);return a}bb[" "]=u;function cb(a,b){a&&this.P(a,b)}y(cb,K);r=cb.prototype;r.target=j;r.relatedTarget=j;r.offsetX=0;r.offsetY=0;r.clientX=0;r.clientY=0;r.screenX=0;r.screenY=0;r.button=0;r.keyCode=0;r.charCode=0;r.ctrlKey=l;r.altKey=l;r.shiftKey=l;r.metaKey=l;r.eb=l;r.ia=j;
r.P=function(a,b){var c=this.type=a.type;K.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(C){var f;a:{try{bb(d.nodeName);f=i;break a}catch(e){}f=l}f||(d=j)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=D||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=D||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.eb=Aa?a.metaKey:a.ctrlKey;this.state=a.state;this.ia=a;a.defaultPrevented&&this.preventDefault();delete this.t};
r.preventDefault=function(){cb.jb.preventDefault.call(this);var a=this.ia;if(a.preventDefault)a.preventDefault();else if(a.returnValue=l,Ra)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var L={},M={},N={},O={};
function P(a,b,c,d,f){if(b)if(v(b))for(var e=0;e<b.length;e++)P(a,b[e],c,d,f);else{var d=!!d,g=M;b in g||(g[b]={a:0,f:0});g=g[b];d in g||(g[d]={a:0,f:0},g.a++);var g=g[d],k=ga(a),s;g.f++;if(g[k]){s=g[k];for(e=0;e<s.length;e++)if(g=s[e],g.I==c&&g.Y==f){if(g.u)break;return}}else s=g[k]=[],g.a++;var n=db,q=Qa?function(a){return n.call(q.src,q.key,a)}:function(a){a=n.call(q.src,q.key,a);if(!a)return a},e=q;e.src=a;g=new Ka;g.P(c,e,a,b,d,f);c=g.key;e.key=c;s.push(g);L[c]=g;N[k]||(N[k]=[]);N[k].push(g);
a.addEventListener?(a==t||!a.ha)&&a.addEventListener(b,e,d):a.attachEvent(b in O?O[b]:O[b]="on"+b,e)}else throw Error("Invalid event type");}function eb(a,b,c,d,f){if(v(b))for(var e=0;e<b.length;e++)eb(a,b[e],c,d,f);else{d=!!d;a:{e=M;if(b in e&&(e=e[b],d in e&&(e=e[d],a=ga(a),e[a]))){a=e[a];break a}a=j}if(a)for(e=0;e<a.length;e++)if(a[e].I==c&&a[e].capture==d&&a[e].Y==f){fb(a[e].key);break}}}
function fb(a){if(L[a]){var b=L[a];if(!b.u){var c=b.src,d=b.type,f=b.ta,e=b.capture;c.removeEventListener?(c==t||!c.ha)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in O?O[d]:O[d]="on"+d,f);c=ga(c);N[c]&&(f=N[c],Xa(f,b),0==f.length&&delete N[c]);b.u=i;if(b=M[d][e][c])b.qa=i,gb(d,e,c,b);delete L[a]}}}
function gb(a,b,c,d){if(!d.R&&d.qa){for(var f=0,e=0;f<d.length;f++)d[f].u?d[f].ta.src=j:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.qa=l;0==e&&(delete M[a][b][c],M[a][b].a--,0==M[a][b].a&&(delete M[a][b],M[a].a--),0==M[a].a&&delete M[a])}}function hb(a,b,c,d,f){var e=1,b=ga(b);if(a[b]){a.f--;a=a[b];a.R?a.R++:a.R=1;try{for(var g=a.length,k=0;k<g;k++){var s=a[k];s&&!s.u&&(e&=ib(s,f)!==l)}}finally{a.R--,gb(c,d,b,a)}}return Boolean(e)}function ib(a,b){a.ea&&fb(a.key);return a.handleEvent(b)}
function db(a,b){if(!L[a])return i;var c=L[a],d=c.type,f=M;if(!(d in f))return i;var f=f[d],e,g;if(!Qa){e=b||aa("window.event");var k=i in f,s=l in f;if(k){if(0>e.keyCode||e.returnValue!=h)return i;a:{var n=l;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(q){n=i}if(n||e.returnValue==h)e.returnValue=i}}n=new cb;n.P(e,this);e=i;try{if(k){for(var m=[],ca=n.currentTarget;ca;ca=ca.parentNode)m.push(ca);g=f[i];g.f=g.a;for(var F=m.length-1;!n.t&&0<=F&&g.f;F--)n.currentTarget=m[F],e&=hb(g,m[F],d,i,n);if(s){g=
f[l];g.f=g.a;for(F=0;!n.t&&F<m.length&&g.f;F++)n.currentTarget=m[F],e&=hb(g,m[F],d,l,n)}}else e=ib(c,n)}finally{m&&(m.length=0)}return e}d=new cb(b,this);return e=ib(c,d)};function jb(a){a=a.className;return w(a)&&a.match(/\S+/g)||[]}function kb(a,b){var c=jb(a),d=$a(arguments,1),f=c.length+d.length;lb(c,d);a.className=c.join(" ");return c.length==f}function lb(a,b){for(var c=0;c<b.length;c++)0<=J(a,b[c])||a.push(b[c])}function mb(a,b,c){var d=jb(a);w(b)?Xa(d,b):v(b)&&(d=Va(d,function(a){return!(0<=J(b,a))}));w(c)&&!(0<=J(d,c))?d.push(c):v(c)&&lb(d,c);a.className=d.join(" ")};var nb=!B||Ja();!C&&!B||B&&Ja()||C&&G("1.9.1");B&&G("9");var ob=B||ya||D;function pb(a,b){function c(b,c){"style"==c?a.style.cssText=b:"class"==c?a.className=b:"for"==c?a.htmlFor=b:c in qb?a.setAttribute(qb[c],b):0==c.lastIndexOf("aria-",0)||0==c.lastIndexOf("data-",0)?a.setAttribute(c,b):a[c]=b}for(var d in b)c.call(h,b[d],d)}var qb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Q(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!nb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',z(g.name),'"');if(g.type){e.push(' type="',z(g.type),'"');var k={};Pa(k,g);g=k;delete g.type}e.push(">");e=e.join("")}e=f.createElement(e);g&&(w(g)?e.className=g:v(g)?kb.apply(j,[e].concat(g)):pb(e,g));if(2<d.length)for(var s=f,n=e,f=function(a){a&&n.appendChild(w(a)?s.createTextNode(a):a)},g=2;g<d.length;g++)if(k=d[g],da(k)&&!(fa(k)&&0<k.nodeType)){var q=Ua,m;a:{if((m=k)&&"number"==
typeof m.length){if(fa(m)){m="function"==typeof m.item||"string"==typeof m.item;break a}if(ea(m)){m="function"==typeof m.item;break a}}m=l}q(m?Za(k):k,f)}else f(k);return e}function rb(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function R(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else rb(a),a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(b))};function sb(){this.Ha=l}y(sb,ab);r=sb.prototype;r.ha=i;r.sa=j;r.addEventListener=function(a,b,c,d){P(this,a,b,c,d)};r.removeEventListener=function(a,b,c,d){eb(this,a,b,c,d)};
r.dispatchEvent=function(a){var b=a.type||a,c=M;if(b in c){if(w(a))a=new K(a,this);else if(a instanceof K)a.target=a.target||this;else{var d=a,a=new K(b,this);Pa(a,d)}var d=1,f,c=c[b],b=i in c,e;if(b){f=[];for(e=this;e;e=e.sa)f.push(e);e=c[i];e.f=e.a;for(var g=f.length-1;!a.t&&0<=g&&e.f;g--)a.currentTarget=f[g],d&=hb(e,f[g],a.type,i,a)&&a.U!=l}if(l in c)if(e=c[l],e.f=e.a,b)for(g=0;!a.t&&g<f.length&&e.f;g++)a.currentTarget=f[g],d&=hb(e,f[g],a.type,l,a)&&a.U!=l;else for(f=this;!a.t&&f&&e.f;f=f.sa)a.currentTarget=
f,d&=hb(e,f,a.type,l,a)&&a.U!=l;a=Boolean(d)}else a=i;return a};function tb(){this.$="Loading images\u2026";this.Xa="Load images";this.Ya="Load more";this.Za="You reached the end";this.o=this.O=l}y(tb,sb);tb.prototype.toElement=function(){var a=Q("div",{id:"board-controls"}),b=Q("button",j,this.$);P(b,"click",this.Pa,l,this);this.s=b;a.appendChild(this.s);return a};tb.prototype.Pa=function(){this.o||(R(this.s,this.$),this.dispatchEvent(ub))};
tb.prototype.kb=function(a){this.o||(a.Va?(this.o=i,R(this.s,this.Za)):0<a.hb?R(this.s,this.$):this.O?R(this.s,this.Ya):R(this.s,this.Xa))};var ub="a";function vb(a,b){var c=document.body.scrollHeight;if(c==h)throw Error("missing height argument");a.style.width=wb(b);a.style.height=wb(c)}function wb(a){"number"==typeof a&&(a=Math.round(a)+"px");return a};function xb(){}y(xb,sb);r=xb.prototype;
r.open=function(){if(!this.l){S=T();this.ra=T();var a=Q("div",{id:"subreddit-picker-background"});vb(a,document.body.scrollWidth);P(a,"click",this.Ka,l,this);var b=Q("div",{id:"subreddit-picker",style:{top:document.body.scrollHeight+10}});a.appendChild(b);var c=Q("input",{id:"subreddit-picker-text-field",placeholder:"Enter subreddit and press return",type:"text"});P(c,"keydown",this.Ta,l,this);b.appendChild(c);for(var c=Q("ul",{id:"subreddit-picker-subreddit-list"}),d=T(),f=0,e=d.length;f<e;f++){var g=
yb(d[f]);c.appendChild(g)}P(c,"click",this.Sa,l,this);this.ya=c;b.appendChild(this.ya);this.l=a;document.body.appendChild(this.l);P(window,"resize",this.N,l,this);this.dispatchEvent(zb)}};r.close=function(){this.l&&(eb(window,"resize",this.N,l,this),kb(this.l,"fade-out"),t.setTimeout(x(function(){var a=this.l;a&&a.parentNode&&a.parentNode.removeChild(a);this.ra=this.l=j},this),300),this.dispatchEvent(Ab))};
r.Ka=function(a){if("subreddit-picker-background"===a.target.getAttribute("id")){this.close();a:{var a=T(),b=this.ra,c=a.length;if(c!==b.length)a=i;else{for(var d=0;d<c;d++)if(0>b.indexOf(a[d])){a=i;break a}a=l}}a&&this.dispatchEvent(Bb)}};
r.Sa=function(a){if(a.target.hasAttribute("data-subreddit-name")){var b=a.target.getAttribute("data-subreddit-name"),c=jb(a.target);0<=J(c,"subreddit-picker-subreddit-add-button")?(mb(a.target,"subreddit-picker-subreddit-add-button","subreddit-picker-subreddit-remove-button"),Cb(b)):(mb(a.target,"subreddit-picker-subreddit-remove-button","subreddit-picker-subreddit-add-button"),a=T(l),b=a.indexOf(b),0>b||(a.splice(b,1),S=a,location.hash=a.join("+")))}};
function yb(a){var b=Q("li","subreddit-picker-subreddit-list-item"),c=Q("button",{"class":"subreddit-picker-subreddit-remove-button","data-subreddit-name":a});R(c,a);b.appendChild(c);return b}r.N=function(){this.l&&vb(this.l,document.body.offsetWidth)};r.Ta=function(a){if(!(13!==a.keyCode&&3!==a.keyCode)){var b=yb(a.target.value);this.ya.appendChild(b);Cb(a.target.value);a.target.value=""}};var Ab="a",zb="b",Bb="c";function Db(){}Db.prototype.toElement=function(){return Q("button",{id:"subreddit-picker-launcher"},"Edit Subreddits")};var Eb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Fb(a){if("function"==typeof a.i)return a.i();if(w(a))return a.split("");if(da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ma(a)};function Gb(a,b){this.j={};this.c=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Gb?(c=a.r(),d=a.i()):(c=Na(a),d=Ma(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}r=Gb.prototype;r.a=0;r.Aa=0;r.i=function(){Hb(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};r.r=function(){Hb(this);return this.c.concat()};r.D=function(a){return U(this.j,a)};
r.remove=function(a){return U(this.j,a)?(delete this.j[a],this.a--,this.Aa++,this.c.length>2*this.a&&Hb(this),i):l};function Hb(a){if(a.a!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];U(a.j,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.a!=a.c.length){for(var f={},c=b=0;b<a.c.length;)d=a.c[b],U(f,d)||(a.c[c++]=d,f[d]=1),b++;a.c.length=c}}r.get=function(a,b){return U(this.j,a)?this.j[a]:b};r.set=function(a,b){U(this.j,a)||(this.a++,this.c.push(a),this.Aa++);this.j[a]=b};r.B=function(){return new Gb(this)};
function U(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ib(a,b){var c;if(a instanceof Ib)this.e=b!==h?b:a.e,Jb(this,a.v),c=a.W,V(this),this.W=c,c=a.F,V(this),this.F=c,Kb(this,a.T),c=a.S,V(this),this.S=c,Lb(this,a.h.B()),c=a.M,V(this),this.M=c;else if(a&&(c=String(a).match(Eb))){this.e=!!b;Jb(this,c[1]||"",i);var d=c[2]||"";V(this);this.W=d?decodeURIComponent(d):"";d=c[3]||"";V(this);this.F=d?decodeURIComponent(d):"";Kb(this,c[4]);d=c[5]||"";V(this);this.S=d?decodeURIComponent(d):"";Lb(this,c[6]||"",i);c=c[7]||"";V(this);this.M=c?decodeURIComponent(c):
""}else this.e=!!b,this.h=new Mb(j,0,this.e)}r=Ib.prototype;r.v="";r.W="";r.F="";r.T=j;r.S="";r.M="";r.Wa=l;r.e=l;r.toString=function(){var a=[],b=this.v;b&&a.push(Nb(b,Ob),":");if(b=this.F){a.push("//");var c=this.W;c&&a.push(Nb(c,Ob),"@");a.push(encodeURIComponent(String(b)));b=this.T;b!=j&&a.push(":",String(b))}if(b=this.S)this.F&&"/"!=b.charAt(0)&&a.push("/"),a.push(Nb(b,"/"==b.charAt(0)?Pb:Qb));(b=this.h.toString())&&a.push("?",b);(b=this.M)&&a.push("#",Nb(b,Rb));return a.join("")};r.B=function(){return new Ib(this)};
function Jb(a,b,c){V(a);a.v=c?b?decodeURIComponent(b):"":b;a.v&&(a.v=a.v.replace(/:$/,""))}function Kb(a,b){V(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.T=b}else a.T=j}function Lb(a,b,c){V(a);b instanceof Mb?(a.h=b,a.h.ca(a.e)):(c||(b=Nb(b,Sb)),a.h=new Mb(b,0,a.e))}function Tb(a,b,c){V(a);v(c)||(c=[String(c)]);Ub(a.h,b,c)}function V(a){if(a.Wa)throw Error("Tried to modify a read-only Uri");}r.ca=function(a){this.e=a;this.h&&this.h.ca(a);return this};
function Nb(a,b){return w(a)?encodeURI(a).replace(b,Vb):j}function Vb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Ob=/[#\/\?@]/g,Qb=/[\#\?:]/g,Pb=/[\#\?]/g,Sb=/[\#\?@]/g,Rb=/#/g;function Mb(a,b,c){this.d=a||j;this.e=!!c}
function W(a){if(!a.b&&(a.b=new Gb,a.a=0,a.d))for(var b=a.d.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=j,e=j;0<=d?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=decodeURIComponent(f.replace(/\+/g," "));f=X(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}r=Mb.prototype;r.b=j;r.a=j;r.add=function(a,b){W(this);this.d=j;var a=X(this,a),c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.a++;return this};
r.remove=function(a){W(this);a=X(this,a);return this.b.D(a)?(this.d=j,this.a-=this.b.get(a).length,this.b.remove(a)):l};r.D=function(a){W(this);a=X(this,a);return this.b.D(a)};r.r=function(){W(this);for(var a=this.b.i(),b=this.b.r(),c=[],d=0;d<b.length;d++)for(var f=a[d],e=0;e<f.length;e++)c.push(b[d]);return c};r.i=function(a){W(this);var b=[];if(a)this.D(a)&&(b=Ya(b,this.b.get(X(this,a))));else for(var a=this.b.i(),c=0;c<a.length;c++)b=Ya(b,a[c]);return b};
r.set=function(a,b){W(this);this.d=j;a=X(this,a);this.D(a)&&(this.a-=this.b.get(a).length);this.b.set(a,[b]);this.a++;return this};r.get=function(a,b){var c=a?this.i(a):[];return 0<c.length?String(c[0]):b};function Ub(a,b,c){a.remove(b);0<c.length&&(a.d=j,a.b.set(X(a,b),Za(c)),a.a+=c.length)}
r.toString=function(){if(this.d)return this.d;if(!this.b)return"";for(var a=[],b=this.b.r(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.i(d),e=0;e<d.length;e++){var g=f;""!==d[e]&&(g+="="+encodeURIComponent(String(d[e])));a.push(g)}return this.d=a.join("&")};r.B=function(){var a=new Mb;a.d=this.d;this.b&&(a.b=this.b.B());return a};function X(a,b){var c=String(b);a.e&&(c=c.toLowerCase());return c}
r.ca=function(a){if(a&&!this.e){W(this);this.d=j;var b=this.b,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),Ub(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(da(b)||w(b))Ua(b,c,this);else{var d;if("function"==typeof b.r)d=b.r();else if("function"!=typeof b.i)if(da(b)||w(b)){d=[];for(var f=b.length,e=0;e<f;e++)d.push(e)}else d=Na(b);else d=h;b=Fb(b);f=b.length;for(e=0;e<f;e++)c.call(this,b[e],d&&d[e])}}this.e=a};function Wb(a,b,c){this.la=c;this.Z=b;this.za=a}Wb.prototype.toElement=function(){var a=Q("div","board-item"),b=Q("a",{"class":"board-item-image-anchor",href:this.la?this.la:this.Z.src}),c=Q("img",{"class":"board-item-image","data-original-src":this.Z.src,src:this.Z.src});b.appendChild(c);a.appendChild(b);b=Q("a",{"class":"board-item-title-anchor",href:"http://www.reddit.com"+this.za.permalink});b.innerHTML=this.za.title;a.appendChild(b);return a};function Xb(a){return Yb(a||arguments.callee.caller,[])}
function Yb(a,b){var c=[];if(0<=J(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Zb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=Zb(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(Yb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Zb(a){if($b[a])return $b[a];a=String(a);if(!$b[a]){var b=/function ([^\(]+)/.exec(a);$b[a]=b?b[1]:"[Anonymous]"}return $b[a]}var $b={};function Y(a,b,c,d,f){this.reset(a,b,c,d,f)}Y.prototype.ib=0;Y.prototype.ka=j;Y.prototype.ja=j;var ac=0;Y.prototype.reset=function(a,b,c,d,f){this.ib="number"==typeof f?f:ac++;this.vb=d||la();this.H=a;this.ab=b;this.tb=c;delete this.ka;delete this.ja};Y.prototype.wa=function(a){this.H=a};function Z(a){this.bb=a}Z.prototype.p=j;Z.prototype.H=j;Z.prototype.X=j;Z.prototype.na=j;function bc(a,b){this.name=a;this.value=b}bc.prototype.toString=function(){return this.name};var cc=new bc("INFO",800),dc=new bc("CONFIG",700),ec=new bc("FINE",500);r=Z.prototype;r.getParent=function(){return this.p};r.Ia=function(){this.X||(this.X={});return this.X};r.wa=function(a){this.H=a};function fc(a){if(a.H)return a.H;if(a.p)return fc(a.p);Ta("Root logger has no level set.");return j}
r.log=function(a,b,c){if(a.value>=fc(this).value){a=this.Ja(a,b,c);b="log:"+a.ab;t.console&&(t.console.timeStamp?t.console.timeStamp(b):t.console.markTimeline&&t.console.markTimeline(b));t.msWriteProfilerMark&&t.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.na)for(var f=0,e=h;e=c.na[f];f++)e(d);b=b.getParent()}}};
r.Ja=function(a,b,c){var d=new Y(a,String(b),this.bb);if(c){d.ka=c;var f;var e=arguments.callee.caller;try{var g;var k=aa("window.location.href");if(w(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:k,stack:"Not available"};else{var s,n,q=l;try{s=c.lineNumber||c.sb||"Not available"}catch(m){s="Not available",q=i}try{n=c.fileName||c.filename||c.sourceURL||k}catch(ca){n="Not available",q=i}g=q||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:s,
fileName:n,stack:c.stack||"Not available"}:c}f="Message: "+z(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+z(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+z(Xb(e)+"-> ")}catch(F){f="Exception trying to expose exception! You win, we lose. "+F}d.ja=f}return d};r.info=function(a,b){this.log(cc,a,b)};var gc={},hc=j;
function ic(a){hc||(hc=new Z(""),gc[""]=hc,hc.wa(dc));var b;if(!(b=gc[a])){b=new Z(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=ic(a.substr(0,c));c.Ia()[d]=b;b.p=c;gc[a]=b}return b};var jc="1000words agricultureporn aviation birdpics cityporn earthporn itookapicture picturechallenge wallpaper wallpapers windowshots".split(" "),S=[];function T(a){"boolean"!==typeof a&&(a=i);return 0===S.length&&a?jc.slice():S.slice()}function Cb(a){var b=T(l);0<=b.indexOf(a)||(b.push(a),S=b,location.hash=b.join("+"))};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function kc(a,b){this.A=[];this.mb=a;this.Ga=b||j}r=kc.prototype;r.q=l;r.G=l;r.J=0;r.xa=l;r.Da=l;r.Ba=0;r.ga=function(a,b){lc(this,a,b);this.J--;0==this.J&&this.q&&mc(this)};function lc(a,b,c){a.q=i;a.ba=c;a.G=!b;mc(a)}function nc(a){if(a.q){if(!a.xa)throw new oc(a);a.xa=l}}function pc(a){return Wa(a.A,function(a){return ea(a[1])})}
function mc(a){a.da&&(a.q&&pc(a))&&(t.clearTimeout(a.da),delete a.da);a.p&&(a.p.Ba--,delete a.p);for(var b=a.ba,c=l,d=l;a.A.length&&0==a.J;){var f=a.A.shift(),e=f[0],g=f[1],f=f[2];if(e=a.G?g:e)try{var k=e.call(f||a.Ga,b);k!==h&&(a.G=a.G&&(k==b||k instanceof Error),a.ba=b=k);b instanceof kc&&(d=i,a.J++)}catch(s){b=s,a.G=i,pc(a)||(c=i)}}a.ba=b;d&&a.J&&(d=b,k=x(a.ga,a,i),e=x(a.ga,a,l),d.A.push([k,e,h]),d.q&&mc(d),b.Da=i);c&&(a.da=t.setTimeout(function(){throw new qc(b);},0))}
function oc(a){H.call(this);this.ob=a}y(oc,H);oc.prototype.message="Already called";function qc(a){H.call(this);this.nb=a;this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")}y(qc,H);function rc(){if(this&&this.va){var a=this.va;a&&"SCRIPT"==a.tagName&&sc(a,i,this.K)}}function sc(a,b,c){c!=j&&t.clearTimeout(c);a.onload=u;a.onerror=u;a.onreadystatechange=u;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function tc(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);H.call(this,c);this.code=a}y(tc,H);function uc(a,b){this.lb=new Ib(a);this.Ca=b?b:"callback";this.K=5E3}var vc=0;
uc.prototype.send=function(a,b,c,d){var f=a||j,e=d||"_"+(vc++).toString(36)+la().toString(36);t._callbacks_||(t._callbacks_={});a=this.lb.B();if(f)for(var g in f)(!f.hasOwnProperty||f.hasOwnProperty(g))&&Tb(a,g,f[g]);b&&(t._callbacks_[e]=function(a){wc(e,i);b.apply(h,arguments)},Tb(a,this.Ca,"_callbacks_."+e));var k=a.toString(),s={timeout:this.K,Ea:i};g=s.document||document;var n=document.createElement("SCRIPT"),a={va:n,K:h},q=new kc(rc,a),m=j,d=s.timeout!=j?s.timeout:5E3;0<d&&(m=window.setTimeout(function(){sc(n,
i);var a=new tc(1,"Timeout reached for loading script "+k);nc(q);lc(q,l,a)},d),a.K=m);n.onload=n.onreadystatechange=function(){if(!n.readyState||"loaded"==n.readyState||"complete"==n.readyState)sc(n,s.Ea||l,m),nc(q),lc(q,i,j)};n.onerror=function(){sc(n,i,m);var a=new tc(0,"Error while loading script "+k);nc(q);lc(q,l,a)};pb(n,{type:"text/javascript",charset:"UTF-8",src:k});a=g.getElementsByTagName("HEAD");(!a||0==a.length?g.documentElement:a[0]).appendChild(n);q.A.push([j,function(){wc(e,l);c&&c(f)},
h]);q.q&&mc(q);return{rb:e,pb:q}};function wc(a,b){t._callbacks_[a]&&(b?delete t._callbacks_[a]:t._callbacks_[a]=u)};function xc(a,b,c){this.w=Q("div",{id:"board"});this.z=[];this.L=0;this.k=[];this.fa=b;this.Fa=a;this.n=[];this.C=0;this.o=this.O=l;this.Q="";this.pa=ic("panoptikos.ui.Board");this.$a=c;this.fb=3E4;this.g=0;P(window,"resize",this.N,l,this);P(this.w,"click",this.La,l,this);B&&(a=Q("link",{href:"board-item-ie.css",rel:"stylesheet",type:"text/css"}),document.head.appendChild(a))}y(xc,sb);r=xc.prototype;
r.La=function(a){if(!a.altKey&&!a.ctrlKey&&!a.metaKey&&!a.shiftKey)if(a.preventDefault(),"board-item-title-anchor"===a.target.className&&a.target.hasAttribute("href"))window.open(a.target.getAttribute("href"));else{if("board-item-image"===a.target.className){var b;b=a.target;ob?b=b.parentElement:(b=b.parentNode,b=fa(b)&&1==b.nodeType?b:j);a.target=b}"board-item-image-anchor"===a.target.className&&a.target.hasAttribute("href")&&window.open(a.target.getAttribute("href"))}};
r.N=function(){clearTimeout(this.gb);this.gb=t.setTimeout(x(this.aa,this),10)};
r.aa=function(){var a=this.w.offsetWidth,b=1,c=this.Fa;a<c?c=a:b+=Math.floor((a-c)/(c+this.fa));this.C!==c&&(this.C=c,a=".board-column {margin-left: "+this.fa+"px; width: "+this.C+"px;}",a+=".board-item {width: "+(this.C-8)+"px;}",this.V?this.V.innerHTML=a:(this.V=Q("style",{type:"text/css"}),this.V.innerHTML=a,document.head.appendChild(this.V)));if(b!==this.L){this.L=b;this.n=[];this.k=[];rb(this.w);for(b=0;b<this.L;b++)a=Q("div","board-column"),this.n.push(a),this.k.push(0),this.w.appendChild(a);
this.pa.info("Rebuilding board with "+this.z.length+" images.");b=0;for(a=this.z.length;b<a;b++)yc(this,this.z[b])}};r.ua=function(){if(!this.o&&!(0<this.g)){this.g++;var a=new Ib("http://www.reddit.com/r/"+T().join("+")+".json"),b=this.Q;V(a);a.h.set("after",b);b=this.$a;V(a);a.h.set("limit",b);a=new uc(a,"jsonp");a.K=this.fb;a.send(j,x(this.Ra,this),x(this.Qa,this))}};
r.Ra=function(a){for(var b=a.data.children,c=0,d=b.length;c<d;c++){var f=b[c].data.url,e=b[c].data.url.match(/^https?:\/\/(?:i\.)?imgur\.com\/([a-zA-Z0-9]+)/);if(e){var f="http://i.imgur.com/"+e[1]+"l.jpg",e="http://i.imgur.com/"+e[1]+".jpg",g=new Image;P(g,"error",x(this.Na,this,[b[c].data]),l,this);P(g,"load",x(this.Oa,this,b[c].data,g,e),l,this)}else g=new Image,P(g,"error",x(this.Ma,this,b[c].data)),P(g,"load",x(this.ma,this,b[c].data,g,g.src));this.g++;g.src=f}this.Q=a.data.after;this.Q||(this.o=
i);this.g--;zc(this)};r.Qa=function(){this.g--;zc(this);alert("Panoptikos cannot retrieve data from Reddit because Reddit is slow or you are not connected to the Internet.")};r.Na=function(){this.g--;zc(this)};r.Oa=function(a,b,c){this.ma(a,b,c)};r.Ma=function(){this.g--;zc(this)};
r.ma=function(a,b,c){81===b.height&&161===b.width&&/^https?:\/\/i\.imgur\.com\//.test(b.src)?(this.pa.log(ec,"Ignoring Imgur\u2019s \u201cImage does not exist\u201d image: "+b.src,h),this.g--):(a=(new Wb(a,b,c)).toElement(),this.z.push(a),yc(this,a),this.g--,this.O=i);zc(this)};function yc(a,b){for(var c,d=c=j,f=0,e=a.k.length;f<e;f++)c===j?(c=a.k[f],d=f):c>a.k[f]&&(c=a.k[f],d=f);c=d;c===j||(!a.n||!a.n[c])||(a.n[c].appendChild(b),a.k[c]=a.n[c].offsetHeight)}
r.Ua=function(){this.C=this.L=0;this.n=[];this.k=[];this.z=[];this.Q="";this.g=0;this.aa();this.ua()};function zc(a){a.dispatchEvent(new Ac(Bc,a,a.g,a.O,a.o))}var Bc="a";function Ac(a,b,c,d,f){K.call(this,a,b);this.qb=d;this.Va=f;this.hb=c}y(Ac,K);function Cc(){var a;a=location.hash.replace(/^#/,"").split("+");for(var b=0,c=a.length;b<c;b++)"string"===typeof a[b]&&/^[0-9a-zA-Z_]+$/.test(a[b])||(a.splice(b,1),c--);a.length||(a=jc.slice());S=a;a=(new Db).toElement();document.body.appendChild(a);P(a,"click",this.cb,l,this);this.m=new xc(328,10,25);document.body.appendChild(this.m.w);this.m.aa();a=new tb;P(this.m,Bc,a.kb,l,a);P(a,ub,this.m.ua,l,this.m);b=a.toElement();document.body.appendChild(b);a.dispatchEvent(ub)}var Dc=["p"],$=t;
!(Dc[0]in $)&&$.execScript&&$.execScript("var "+Dc[0]);for(var Ec;Dc.length&&(Ec=Dc.shift());)!Dc.length&&Cc!==h?$[Ec]=Cc:$=$[Ec]?$[Ec]:$[Ec]={};Cc.prototype.cb=function(a){a.preventDefault();a=new xb;P(a,Bb,this.m.Ua,l,this.m);a.open()};
