var g=void 0,i=!0,j=null,k=!1,r,t=this;function aa(a){for(var a=a.split("."),b=t,c;c=a.shift();)if(b[c]!=j)b=b[c];else return j;return b}function u(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function v(a){return"array"==ba(a)}function da(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function w(a){return"string"==typeof a}function ea(a){return"function"==ba(a)}function fa(a){var b=typeof a;return"object"==b&&a!=j||"function"==b}function ga(a){return a[ha]||(a[ha]=++ia)}var ha="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ia=0;
function ja(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function x(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return x.apply(j,arguments)}var la=Date.now||function(){return+new Date};
function y(a,b){function c(){}c.prototype=b.prototype;a.mb=b.prototype;a.prototype=new c};function ma(a,b){for(var c=1;c<arguments.length;c++)var d=String(arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,d);return a}function z(a){if(!na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(oa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(pa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(qa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ra,"&quot;"));return a}var oa=/&/g,pa=/</g,qa=/>/g,ra=/\"/g,na=/[&<>\"]/;var A,sa,ta,ua;function va(){return t.navigator?t.navigator.userAgent:j}ua=ta=sa=A=k;var wa;if(wa=va()){var xa=t.navigator;A=0==wa.indexOf("Opera");sa=!A&&-1!=wa.indexOf("MSIE");ta=!A&&-1!=wa.indexOf("WebKit");ua=!A&&!ta&&"Gecko"==xa.product}var ya=A,B=sa,C=ua,D=ta,za=t.navigator,Aa=-1!=(za&&za.platform||"").indexOf("Mac"),Ba;
a:{var Ca="",E;if(ya&&t.opera)var Da=t.opera.version,Ca="function"==typeof Da?Da():Da;else if(C?E=/rv\:([^\);]+)(\)|;)/:B?E=/MSIE\s+([^\);]+)(\)|;)/:D&&(E=/WebKit\/(\S+)/),E)var Ea=E.exec(va()),Ca=Ea?Ea[1]:"";if(B){var Fa,Ga=t.document;Fa=Ga?Ga.documentMode:g;if(Fa>parseFloat(Ca)){Ba=String(Fa);break a}}Ba=Ca}var Ha={};
function G(a){var b;if(!(b=Ha[a])){b=0;for(var c=String(Ba).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var h=c[e]||"",m=d[e]||"",s=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var q=s.exec(h)||["","",""],n=l.exec(m)||["","",""];if(0==q[0].length&&0==n[0].length)break;b=((0==q[1].length?0:parseInt(q[1],10))<(0==n[1].length?0:parseInt(n[1],10))?-1:(0==q[1].length?0:parseInt(q[1],
10))>(0==n[1].length?0:parseInt(n[1],10))?1:0)||((0==q[2].length)<(0==n[2].length)?-1:(0==q[2].length)>(0==n[2].length)?1:0)||(q[2]<n[2]?-1:q[2]>n[2]?1:0)}while(0==b)}b=Ha[a]=0<=b}return b}var Ia={};function Ja(){return Ia[9]||(Ia[9]=B&&!!document.documentMode&&9<=document.documentMode)};function Ka(){}var La=0;r=Ka.prototype;r.key=0;r.v=k;r.ga=k;r.R=function(a,b,c,d,f,e){if(ea(a))this.qa=i;else if(a&&a.handleEvent&&ea(a.handleEvent))this.qa=k;else throw Error("Invalid listener argument");this.K=a;this.va=b;this.src=c;this.type=d;this.capture=!!f;this.$=e;this.ga=k;this.key=++La;this.v=k};r.handleEvent=function(a){return this.qa?this.K.call(this.$||this.src,a):this.K.handleEvent.call(this.K,a)};function Ma(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Na(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Pa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Oa.length;e++)c=Oa[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};!B||Ja();var Qa=!B||Ja(),Ra=B&&!G("8");!D||G("528");C&&G("1.9b")||B&&G("8")||ya&&G("9.5")||D&&G("528");C&&!G("8")||B&&G("9");function H(a){Error.captureStackTrace?Error.captureStackTrace(this,H):this.stack=Error().stack||"";a&&(this.message=String(a))}y(H,Error);H.prototype.name="CustomError";function Sa(a,b){b.unshift(a);H.call(this,ma.apply(j,b));b.shift();this.xb=a}y(Sa,H);Sa.prototype.name="AssertionError";function Ta(a,b){throw new Sa("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var I=Array.prototype,J=I.indexOf?function(a,b,c){return I.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(w(a))return!w(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ua=I.forEach?function(a,b,c){I.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=w(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},Va=I.filter?function(a,b,c){return I.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,h=w(a)?a.split(""):
a,m=0;m<d;m++)if(m in h){var s=h[m];b.call(c,s,m,a)&&(f[e++]=s)}return f},Wa=I.some?function(a,b,c){return I.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=w(a)?a.split(""):a,e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return i;return k};function Xa(a,b){var c=J(a,b);0<=c&&I.splice.call(a,c,1)}function Ya(a){return I.concat.apply(I,arguments)}function Za(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function $a(a,b,c){return 2>=arguments.length?I.slice.call(a,b):I.slice.call(a,b,c)};function ab(){this.Ka=k};function K(a,b){this.type=a;this.currentTarget=this.target=b}K.prototype.u=k;K.prototype.defaultPrevented=k;K.prototype.W=i;K.prototype.preventDefault=function(){this.defaultPrevented=i;this.W=k};function bb(a){bb[" "](a);return a}bb[" "]=u;function cb(a,b){a&&this.R(a,b)}y(cb,K);r=cb.prototype;r.target=j;r.relatedTarget=j;r.offsetX=0;r.offsetY=0;r.clientX=0;r.clientY=0;r.screenX=0;r.screenY=0;r.button=0;r.keyCode=0;r.charCode=0;r.ctrlKey=k;r.altKey=k;r.shiftKey=k;r.metaKey=k;r.hb=k;r.ka=j;
r.R=function(a,b){var c=this.type=a.type;K.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(C){var f;a:{try{bb(d.nodeName);f=i;break a}catch(e){}f=k}f||(d=j)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=D||a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=D||a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.hb=Aa?a.metaKey:a.ctrlKey;this.state=a.state;this.ka=a;a.defaultPrevented&&this.preventDefault();delete this.u};
r.preventDefault=function(){cb.mb.preventDefault.call(this);var a=this.ka;if(a.preventDefault)a.preventDefault();else if(a.returnValue=k,Ra)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var L={},M={},N={},O={};
function P(a,b,c,d,f){if(b)if(v(b))for(var e=0;e<b.length;e++)P(a,b[e],c,d,f);else{var d=!!d,h=M;b in h||(h[b]={a:0,f:0});h=h[b];d in h||(h[d]={a:0,f:0},h.a++);var h=h[d],m=ga(a),s;h.f++;if(h[m]){s=h[m];for(e=0;e<s.length;e++)if(h=s[e],h.K==c&&h.$==f){if(h.v)break;return}}else s=h[m]=[],h.a++;var l=db,q=Qa?function(a){return l.call(q.src,q.key,a)}:function(a){a=l.call(q.src,q.key,a);if(!a)return a},e=q;e.src=a;h=new Ka;h.R(c,e,a,b,d,f);c=h.key;e.key=c;s.push(h);L[c]=h;N[m]||(N[m]=[]);N[m].push(h);
a.addEventListener?(a==t||!a.ja)&&a.addEventListener(b,e,d):a.attachEvent(b in O?O[b]:O[b]="on"+b,e)}else throw Error("Invalid event type");}function eb(a,b,c,d,f){if(v(b))for(var e=0;e<b.length;e++)eb(a,b[e],c,d,f);else{d=!!d;a:{e=M;if(b in e&&(e=e[b],d in e&&(e=e[d],a=ga(a),e[a]))){a=e[a];break a}a=j}if(a)for(e=0;e<a.length;e++)if(a[e].K==c&&a[e].capture==d&&a[e].$==f){fb(a[e].key);break}}}
function fb(a){if(L[a]){var b=L[a];if(!b.v){var c=b.src,d=b.type,f=b.va,e=b.capture;c.removeEventListener?(c==t||!c.ja)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in O?O[d]:O[d]="on"+d,f);c=ga(c);N[c]&&(f=N[c],Xa(f,b),0==f.length&&delete N[c]);b.v=i;if(b=M[d][e][c])b.sa=i,gb(d,e,c,b);delete L[a]}}}
function gb(a,b,c,d){if(!d.T&&d.sa){for(var f=0,e=0;f<d.length;f++)d[f].v?d[f].va.src=j:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.sa=k;0==e&&(delete M[a][b][c],M[a][b].a--,0==M[a][b].a&&(delete M[a][b],M[a].a--),0==M[a].a&&delete M[a])}}function hb(a,b,c,d,f){var e=1,b=ga(b);if(a[b]){a.f--;a=a[b];a.T?a.T++:a.T=1;try{for(var h=a.length,m=0;m<h;m++){var s=a[m];s&&!s.v&&(e&=ib(s,f)!==k)}}finally{a.T--,gb(c,d,b,a)}}return Boolean(e)}function ib(a,b){a.ga&&fb(a.key);return a.handleEvent(b)}
function db(a,b){if(!L[a])return i;var c=L[a],d=c.type,f=M;if(!(d in f))return i;var f=f[d],e,h;if(!Qa){e=b||aa("window.event");var m=i in f,s=k in f;if(m){if(0>e.keyCode||e.returnValue!=g)return i;a:{var l=k;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(q){l=i}if(l||e.returnValue==g)e.returnValue=i}}l=new cb;l.R(e,this);e=i;try{if(m){for(var n=[],ca=l.currentTarget;ca;ca=ca.parentNode)n.push(ca);h=f[i];h.f=h.a;for(var F=n.length-1;!l.u&&0<=F&&h.f;F--)l.currentTarget=n[F],e&=hb(h,n[F],d,i,l);if(s){h=
f[k];h.f=h.a;for(F=0;!l.u&&F<n.length&&h.f;F++)l.currentTarget=n[F],e&=hb(h,n[F],d,k,l)}}else e=ib(c,l)}finally{n&&(n.length=0)}return e}d=new cb(b,this);return e=ib(c,d)};function jb(a){a=a.className;return w(a)&&a.match(/\S+/g)||[]}function kb(a,b){var c=jb(a),d=$a(arguments,1),f=c.length+d.length;lb(c,d);a.className=c.join(" ");return c.length==f}function lb(a,b){for(var c=0;c<b.length;c++)0<=J(a,b[c])||a.push(b[c])}function mb(a,b,c){var d=jb(a);w(b)?Xa(d,b):v(b)&&(d=Va(d,function(a){return!(0<=J(b,a))}));w(c)&&!(0<=J(d,c))?d.push(c):v(c)&&lb(d,c);a.className=d.join(" ")};var nb=!B||Ja();!C&&!B||B&&Ja()||C&&G("1.9.1");B&&G("9");var ob=B||ya||D;function pb(a,b){function c(b,c){"style"==c?a.style.cssText=b:"class"==c?a.className=b:"for"==c?a.htmlFor=b:c in qb?a.setAttribute(qb[c],b):0==c.lastIndexOf("aria-",0)||0==c.lastIndexOf("data-",0)?a.setAttribute(c,b):a[c]=b}for(var d in b)c.call(g,b[d],d)}var qb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Q(a,b,c){var d=arguments,f=d[0],e=d[1];if(!nb&&e&&(e.name||e.type)){f=["<",f];e.name&&f.push(' name="',z(e.name),'"');if(e.type){f.push(' type="',z(e.type),'"');var h={};Pa(h,e);e=h;delete e.type}f.push(">");f=f.join("")}f=document.createElement(f);e&&(w(e)?f.className=e:v(e)?kb.apply(j,[f].concat(e)):pb(f,e));if(2<d.length)for(var m=f,s=document,e=function(a){a&&m.appendChild(w(a)?s.createTextNode(a):a)},h=2;h<d.length;h++){var l=d[h];if(da(l)&&!(fa(l)&&0<l.nodeType)){var q=Ua,n;a:{if((n=
l)&&"number"==typeof n.length){if(fa(n)){n="function"==typeof n.item||"string"==typeof n.item;break a}if(ea(n)){n="function"==typeof n.item;break a}}n=k}q(n?Za(l):l,e)}else e(l)}return f}function rb(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function R(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else rb(a),a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(b))};function sb(){this.Ka=k}y(sb,ab);r=sb.prototype;r.ja=i;r.ua=j;r.addEventListener=function(a,b,c,d){P(this,a,b,c,d)};r.removeEventListener=function(a,b,c,d){eb(this,a,b,c,d)};
r.dispatchEvent=function(a){var b=a.type||a,c=M;if(b in c){if(w(a))a=new K(a,this);else if(a instanceof K)a.target=a.target||this;else{var d=a,a=new K(b,this);Pa(a,d)}var d=1,f,c=c[b],b=i in c,e;if(b){f=[];for(e=this;e;e=e.ua)f.push(e);e=c[i];e.f=e.a;for(var h=f.length-1;!a.u&&0<=h&&e.f;h--)a.currentTarget=f[h],d&=hb(e,f[h],a.type,i,a)&&a.W!=k}if(k in c)if(e=c[k],e.f=e.a,b)for(h=0;!a.u&&h<f.length&&e.f;h++)a.currentTarget=f[h],d&=hb(e,f[h],a.type,k,a)&&a.W!=k;else for(f=this;!a.u&&f&&e.f;f=f.ua)a.currentTarget=
f,d&=hb(e,f,a.type,k,a)&&a.W!=k;a=Boolean(d)}else a=i;return a};function tb(){this.ba="Loading images\u2026";this.$a="Load images";this.ab="Load more";this.bb="You reached the end";this.o=this.Q=k}y(tb,sb);tb.prototype.G=function(){var a=Q("div",{id:"board-controls"}),b=Q("button",j,this.ba);P(b,"click",this.Sa,k,this);this.t=b;a.appendChild(this.t);return a};tb.prototype.Sa=function(){this.o||(R(this.t,this.ba),this.dispatchEvent(ub))};
tb.prototype.nb=function(a){this.o||(a.Ya?(this.o=i,R(this.t,this.bb)):0<a.kb?R(this.t,this.ba):this.Q?R(this.t,this.ab):R(this.t,this.$a))};var ub="a";function vb(a,b){var c=document.body.scrollHeight;if(c==g)throw Error("missing height argument");a.style.width=wb(b);a.style.height=wb(c)}function wb(a){"number"==typeof a&&(a=Math.round(a)+"px");return a};function xb(){}y(xb,sb);r=xb.prototype;
r.open=function(){if(!this.l){S=T();this.ta=T();var a=Q("div",{id:"subreddit-picker-background"});vb(a,document.body.scrollWidth);P(a,"click",this.Na,k,this);var b=Q("div",{id:"subreddit-picker",style:{top:document.body.scrollHeight+10}});a.appendChild(b);var c=Q("input",{id:"subreddit-picker-text-field",placeholder:"Enter subreddit and press return",type:"text"});P(c,"keydown",this.Wa,k,this);b.appendChild(c);for(var c=Q("ul",{id:"subreddit-picker-subreddit-list"}),d=T(),f=0,e=d.length;f<e;f++){var h=
yb(d[f]);c.appendChild(h)}P(c,"click",this.Va,k,this);this.Aa=c;b.appendChild(this.Aa);this.l=a;document.body.appendChild(this.l);P(window,"resize",this.P,k,this);this.dispatchEvent(zb)}};r.close=function(){this.l&&(eb(window,"resize",this.P,k,this),kb(this.l,"fade-out"),t.setTimeout(x(function(){var a=this.l;a&&a.parentNode&&a.parentNode.removeChild(a);this.ta=this.l=j},this),300),this.dispatchEvent(Ab))};
r.Na=function(a){if("subreddit-picker-background"===a.target.getAttribute("id")){this.close();a:{var a=T(),b=this.ta,c=a.length;if(c!==b.length)a=i;else{for(var d=0;d<c;d++)if(0>b.indexOf(a[d])){a=i;break a}a=k}}a&&this.dispatchEvent(Bb)}};
r.Va=function(a){if(a.target.hasAttribute("data-subreddit-name")){var b=a.target.getAttribute("data-subreddit-name"),c=jb(a.target);0<=J(c,"subreddit-picker-subreddit-add-button")?(mb(a.target,"subreddit-picker-subreddit-add-button","subreddit-picker-subreddit-remove-button"),Cb(b)):(mb(a.target,"subreddit-picker-subreddit-remove-button","subreddit-picker-subreddit-add-button"),a=T(k),b=a.indexOf(b),0>b||(a.splice(b,1),S=a,location.hash=a.join("+")))}};
function yb(a){var b=Q("li","subreddit-picker-subreddit-list-item"),c=Q("button",{"class":"subreddit-picker-subreddit-remove-button","data-subreddit-name":a});R(c,a);b.appendChild(c);return b}r.P=function(){this.l&&vb(this.l,document.body.offsetWidth)};r.Wa=function(a){if(!(13!==a.keyCode&&3!==a.keyCode)){var b=yb(a.target.value);this.Aa.appendChild(b);Cb(a.target.value);a.target.value=""}};var Ab="a",zb="b",Bb="c";function Db(){}Db.prototype.G=function(){return Q("button",{id:"subreddit-picker-launcher"},"Edit Subreddits")};var Eb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Fb(a){if("function"==typeof a.i)return a.i();if(w(a))return a.split("");if(da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ma(a)};function Gb(a,b){this.j={};this.c=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Gb?(c=a.s(),d=a.i()):(c=Na(a),d=Ma(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}r=Gb.prototype;r.a=0;r.Ca=0;r.i=function(){Hb(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};r.s=function(){Hb(this);return this.c.concat()};r.F=function(a){return U(this.j,a)};
r.remove=function(a){return U(this.j,a)?(delete this.j[a],this.a--,this.Ca++,this.c.length>2*this.a&&Hb(this),i):k};function Hb(a){if(a.a!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];U(a.j,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.a!=a.c.length){for(var f={},c=b=0;b<a.c.length;)d=a.c[b],U(f,d)||(a.c[c++]=d,f[d]=1),b++;a.c.length=c}}r.get=function(a,b){return U(this.j,a)?this.j[a]:b};r.set=function(a,b){U(this.j,a)||(this.a++,this.c.push(a),this.Ca++);this.j[a]=b};r.C=function(){return new Gb(this)};
function U(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ib(a,b){var c;if(a instanceof Ib)this.e=b!==g?b:a.e,Jb(this,a.w),c=a.Y,V(this),this.Y=c,c=a.H,V(this),this.H=c,Kb(this,a.V),c=a.U,V(this),this.U=c,Lb(this,a.h.C()),c=a.O,V(this),this.O=c;else if(a&&(c=String(a).match(Eb))){this.e=!!b;Jb(this,c[1]||"",i);var d=c[2]||"";V(this);this.Y=d?decodeURIComponent(d):"";d=c[3]||"";V(this);this.H=d?decodeURIComponent(d):"";Kb(this,c[4]);d=c[5]||"";V(this);this.U=d?decodeURIComponent(d):"";Lb(this,c[6]||"",i);c=c[7]||"";V(this);this.O=c?decodeURIComponent(c):
""}else this.e=!!b,this.h=new Mb(j,0,this.e)}r=Ib.prototype;r.w="";r.Y="";r.H="";r.V=j;r.U="";r.O="";r.Za=k;r.e=k;r.toString=function(){var a=[],b=this.w;b&&a.push(Nb(b,Ob),":");if(b=this.H){a.push("//");var c=this.Y;c&&a.push(Nb(c,Ob),"@");a.push(encodeURIComponent(String(b)));b=this.V;b!=j&&a.push(":",String(b))}if(b=this.U)this.H&&"/"!=b.charAt(0)&&a.push("/"),a.push(Nb(b,"/"==b.charAt(0)?Pb:Qb));(b=this.h.toString())&&a.push("?",b);(b=this.O)&&a.push("#",Nb(b,Rb));return a.join("")};r.C=function(){return new Ib(this)};
function Jb(a,b,c){V(a);a.w=c?b?decodeURIComponent(b):"":b;a.w&&(a.w=a.w.replace(/:$/,""))}function Kb(a,b){V(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.V=b}else a.V=j}function Lb(a,b,c){V(a);b instanceof Mb?(a.h=b,a.h.ea(a.e)):(c||(b=Nb(b,Sb)),a.h=new Mb(b,0,a.e))}function Tb(a,b,c){V(a);v(c)||(c=[String(c)]);Ub(a.h,b,c)}function V(a){if(a.Za)throw Error("Tried to modify a read-only Uri");}r.ea=function(a){this.e=a;this.h&&this.h.ea(a);return this};
function Nb(a,b){return w(a)?encodeURI(a).replace(b,Vb):j}function Vb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Ob=/[#\/\?@]/g,Qb=/[\#\?:]/g,Pb=/[\#\?]/g,Sb=/[\#\?@]/g,Rb=/#/g;function Mb(a,b,c){this.d=a||j;this.e=!!c}
function W(a){if(!a.b&&(a.b=new Gb,a.a=0,a.d))for(var b=a.d.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=j,e=j;0<=d?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=decodeURIComponent(f.replace(/\+/g," "));f=X(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}r=Mb.prototype;r.b=j;r.a=j;r.add=function(a,b){W(this);this.d=j;var a=X(this,a),c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.a++;return this};
r.remove=function(a){W(this);a=X(this,a);return this.b.F(a)?(this.d=j,this.a-=this.b.get(a).length,this.b.remove(a)):k};r.F=function(a){W(this);a=X(this,a);return this.b.F(a)};r.s=function(){W(this);for(var a=this.b.i(),b=this.b.s(),c=[],d=0;d<b.length;d++)for(var f=a[d],e=0;e<f.length;e++)c.push(b[d]);return c};r.i=function(a){W(this);var b=[];if(a)this.F(a)&&(b=Ya(b,this.b.get(X(this,a))));else for(var a=this.b.i(),c=0;c<a.length;c++)b=Ya(b,a[c]);return b};
r.set=function(a,b){W(this);this.d=j;a=X(this,a);this.F(a)&&(this.a-=this.b.get(a).length);this.b.set(a,[b]);this.a++;return this};r.get=function(a,b){var c=a?this.i(a):[];return 0<c.length?String(c[0]):b};function Ub(a,b,c){a.remove(b);0<c.length&&(a.d=j,a.b.set(X(a,b),Za(c)),a.a+=c.length)}
r.toString=function(){if(this.d)return this.d;if(!this.b)return"";for(var a=[],b=this.b.s(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.i(d),e=0;e<d.length;e++){var h=f;""!==d[e]&&(h+="="+encodeURIComponent(String(d[e])));a.push(h)}return this.d=a.join("&")};r.C=function(){var a=new Mb;a.d=this.d;this.b&&(a.b=this.b.C());return a};function X(a,b){var c=String(b);a.e&&(c=c.toLowerCase());return c}
r.ea=function(a){if(a&&!this.e){W(this);this.d=j;var b=this.b,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),Ub(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(da(b)||w(b))Ua(b,c,this);else{var d;if("function"==typeof b.s)d=b.s();else if("function"!=typeof b.i)if(da(b)||w(b)){d=[];for(var f=b.length,e=0;e<f;e++)d.push(e)}else d=Na(b);else d=g;b=Fb(b);f=b.length;for(e=0;e<f;e++)c.call(this,b[e],d&&d[e])}}this.e=a};function Wb(a,b,c){this.na=c;this.aa=b;this.Ba=a}Wb.prototype.G=function(){var a=Q("div","board-item"),b=Q("a",{"class":"board-item-image-anchor",href:this.na?this.na:this.aa.src}),c=Q("img",{"class":"board-item-image","data-original-src":this.aa.src,src:this.aa.src});b.appendChild(c);a.appendChild(b);b=Q("a",{"class":"board-item-title-anchor",href:"http://www.reddit.com"+this.Ba.permalink});b.innerHTML=this.Ba.title;a.appendChild(b);return a};function Xb(a){return Yb(a||arguments.callee.caller,[])}
function Yb(a,b){var c=[];if(0<=J(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Zb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=Zb(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(Yb(a.caller,b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Zb(a){if($b[a])return $b[a];a=String(a);if(!$b[a]){var b=/function ([^\(]+)/.exec(a);$b[a]=b?b[1]:"[Anonymous]"}return $b[a]}var $b={};function Y(a,b,c,d,f){this.reset(a,b,c,d,f)}Y.prototype.lb=0;Y.prototype.ma=j;Y.prototype.la=j;var ac=0;Y.prototype.reset=function(a,b,c,d,f){this.lb="number"==typeof f?f:ac++;this.yb=d||la();this.J=a;this.eb=b;this.wb=c;delete this.ma;delete this.la};Y.prototype.ya=function(a){this.J=a};function Z(a){this.fb=a}Z.prototype.p=j;Z.prototype.J=j;Z.prototype.Z=j;Z.prototype.pa=j;function bc(a,b){this.name=a;this.value=b}bc.prototype.toString=function(){return this.name};var cc=new bc("INFO",800),dc=new bc("CONFIG",700),ec=new bc("FINE",500);r=Z.prototype;r.getParent=function(){return this.p};r.La=function(){this.Z||(this.Z={});return this.Z};r.ya=function(a){this.J=a};function fc(a){if(a.J)return a.J;if(a.p)return fc(a.p);Ta("Root logger has no level set.");return j}
r.log=function(a,b,c){if(a.value>=fc(this).value){a=this.Ma(a,b,c);b="log:"+a.eb;t.console&&(t.console.timeStamp?t.console.timeStamp(b):t.console.markTimeline&&t.console.markTimeline(b));t.msWriteProfilerMark&&t.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.pa)for(var f=0,e=g;e=c.pa[f];f++)e(d);b=b.getParent()}}};
r.Ma=function(a,b,c){var d=new Y(a,String(b),this.fb);if(c){d.ma=c;var f;var e=arguments.callee.caller;try{var h;var m=aa("window.location.href");if(w(c))h={message:c,name:"Unknown error",lineNumber:"Not available",fileName:m,stack:"Not available"};else{var s,l,q=k;try{s=c.lineNumber||c.vb||"Not available"}catch(n){s="Not available",q=i}try{l=c.fileName||c.filename||c.sourceURL||m}catch(ca){l="Not available",q=i}h=q||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:s,
fileName:l,stack:c.stack||"Not available"}:c}f="Message: "+z(h.message)+'\nUrl: <a href="view-source:'+h.fileName+'" target="_new">'+h.fileName+"</a>\nLine: "+h.lineNumber+"\n\nBrowser stack:\n"+z(h.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+z(Xb(e)+"-> ")}catch(F){f="Exception trying to expose exception! You win, we lose. "+F}d.la=f}return d};r.info=function(a,b){this.log(cc,a,b)};var gc={},hc=j;
function ic(a){hc||(hc=new Z(""),gc[""]=hc,hc.ya(dc));var b;if(!(b=gc[a])){b=new Z(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=ic(a.substr(0,c));c.La()[d]=b;b.p=c;gc[a]=b}return b};var jc="1000words agricultureporn aviation birdpics cityporn earthporn itookapicture picturechallenge wallpaper wallpapers windowshots".split(" "),S=[];function T(a){"boolean"!==typeof a&&(a=i);return 0===S.length&&a?jc.slice():S.slice()}function Cb(a){var b=T(k);0<=b.indexOf(a)||(b.push(a),S=b,location.hash=b.join("+"))};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function kc(a,b){this.B=[];this.pb=a;this.Ja=b||j}r=kc.prototype;r.r=k;r.I=k;r.L=0;r.za=k;r.Ga=k;r.Ea=0;r.ia=function(a,b){lc(this,a,b);this.L--;0==this.L&&this.r&&mc(this)};function lc(a,b,c){a.r=i;a.da=c;a.I=!b;mc(a)}function nc(a){if(a.r){if(!a.za)throw new oc(a);a.za=k}}function pc(a){return Wa(a.B,function(a){return ea(a[1])})}
function mc(a){a.fa&&(a.r&&pc(a))&&(t.clearTimeout(a.fa),delete a.fa);a.p&&(a.p.Ea--,delete a.p);for(var b=a.da,c=k,d=k;a.B.length&&0==a.L;){var f=a.B.shift(),e=f[0],h=f[1],f=f[2];if(e=a.I?h:e)try{var m=e.call(f||a.Ja,b);m!==g&&(a.I=a.I&&(m==b||m instanceof Error),a.da=b=m);b instanceof kc&&(d=i,a.L++)}catch(s){b=s,a.I=i,pc(a)||(c=i)}}a.da=b;d&&a.L&&(d=b,m=x(a.ia,a,i),e=x(a.ia,a,k),d.B.push([m,e,g]),d.r&&mc(d),b.Ga=i);c&&(a.fa=t.setTimeout(function(){throw new qc(b);},0))}
function oc(a){H.call(this);this.rb=a}y(oc,H);oc.prototype.message="Already called";function qc(a){H.call(this);this.qb=a;this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")}y(qc,H);function rc(){if(this&&this.xa){var a=this.xa;a&&"SCRIPT"==a.tagName&&sc(a,i,this.M)}}function sc(a,b,c){c!=j&&t.clearTimeout(c);a.onload=u;a.onerror=u;a.onreadystatechange=u;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function tc(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);H.call(this,c);this.code=a}y(tc,H);function uc(a,b){this.ob=new Ib(a);this.Fa=b?b:"callback";this.M=5E3}var vc=0;
uc.prototype.send=function(a,b,c,d){var f=a||j,e=d||"_"+(vc++).toString(36)+la().toString(36);t._callbacks_||(t._callbacks_={});a=this.ob.C();if(f)for(var h in f)(!f.hasOwnProperty||f.hasOwnProperty(h))&&Tb(a,h,f[h]);b&&(t._callbacks_[e]=function(a){wc(e,i);b.apply(g,arguments)},Tb(a,this.Fa,"_callbacks_."+e));var m=a.toString(),s={timeout:this.M,Ha:i};h=s.document||document;var l=document.createElement("SCRIPT"),a={xa:l,M:g},q=new kc(rc,a),n=j,d=s.timeout!=j?s.timeout:5E3;0<d&&(n=window.setTimeout(function(){sc(l,
i);var a=new tc(1,"Timeout reached for loading script "+m);nc(q);lc(q,k,a)},d),a.M=n);l.onload=l.onreadystatechange=function(){if(!l.readyState||"loaded"==l.readyState||"complete"==l.readyState)sc(l,s.Ha||k,n),nc(q),lc(q,i,j)};l.onerror=function(){sc(l,i,n);var a=new tc(0,"Error while loading script "+m);nc(q);lc(q,k,a)};pb(l,{type:"text/javascript",charset:"UTF-8",src:m});a=h.getElementsByTagName("HEAD");(!a||0==a.length?h.documentElement:a[0]).appendChild(l);q.B.push([j,function(){wc(e,k);c&&c(f)},
g]);q.r&&mc(q);return{ub:e,sb:q}};function wc(a,b){t._callbacks_[a]&&(b?delete t._callbacks_[a]:t._callbacks_[a]=u)};function xc(a,b,c){this.z=Q("div",{id:"board"});this.A=[];this.N=0;this.k=[];this.ha=b;this.Ia=a;this.n=[];this.D=0;this.o=this.Q=k;this.S="";this.ra=ic("panoptikos.ui.Board");this.cb=c;this.ib=3E4;this.g=0;P(window,"resize",this.P,k,this);P(this.z,"click",this.Oa,k,this);B&&(a=Q("link",{href:"board-item-ie.css",rel:"stylesheet",type:"text/css"}),document.head.appendChild(a))}y(xc,sb);r=xc.prototype;
r.Oa=function(a){if(!a.altKey&&!a.ctrlKey&&!a.metaKey&&!a.shiftKey)if(a.preventDefault(),"board-item-title-anchor"===a.target.className&&a.target.hasAttribute("href"))window.open(a.target.getAttribute("href"));else{if("board-item-image"===a.target.className){var b;b=a.target;ob?b=b.parentElement:(b=b.parentNode,b=fa(b)&&1==b.nodeType?b:j);a.target=b}"board-item-image-anchor"===a.target.className&&a.target.hasAttribute("href")&&window.open(a.target.getAttribute("href"))}};
r.P=function(){clearTimeout(this.jb);this.jb=t.setTimeout(x(this.ca,this),10)};
r.ca=function(){var a=this.z.offsetWidth,b=1,c=this.Ia;a<c?c=a:b+=Math.floor((a-c)/(c+this.ha));this.D!==c&&(this.D=c,a=".board-column {margin-left: "+this.ha+"px; width: "+this.D+"px;}",a+=".board-item {width: "+(this.D-8)+"px;}",this.X?this.X.innerHTML=a:(this.X=Q("style",{type:"text/css"}),this.X.innerHTML=a,document.head.appendChild(this.X)));if(b!==this.N){this.N=b;this.n=[];this.k=[];rb(this.z);for(b=0;b<this.N;b++)a=Q("div","board-column"),this.n.push(a),this.k.push(0),this.z.appendChild(a);
this.ra.info("Rebuilding board with "+this.A.length+" images.");b=0;for(a=this.A.length;b<a;b++)yc(this,this.A[b])}};r.wa=function(){if(!this.o&&!(0<this.g)){this.g++;var a=new Ib("http://www.reddit.com/r/"+T().join("+")+".json"),b=this.S;V(a);a.h.set("after",b);b=this.cb;V(a);a.h.set("limit",b);a=new uc(a,"jsonp");a.M=this.ib;a.send(j,x(this.Ua,this),x(this.Ta,this))}};
r.Ua=function(a){for(var b=a.data.children,c=0,d=b.length;c<d;c++){var f=b[c].data.url,e=b[c].data.url.match(/^https?:\/\/(?:i\.)?imgur\.com\/([a-zA-Z0-9]+)(\.[a-zA-Z0-9]+)?/);if(e){e[2]&&".gif"===e[2]?e=f="http://i.imgur.com/"+e[1]+".gif":e[2]&&".gif"!==e[2]?(f="http://i.imgur.com/"+e[1]+"l"+e[2],e="http://i.imgur.com/"+e[1]+e[2]):(f="http://i.imgur.com/"+e[1]+"l.jpg",e="http://i.imgur.com/"+e[1]+".jpg");var h=new Image;P(h,"error",x(this.Qa,this,[b[c].data]),k,this);P(h,"load",x(this.Ra,this,b[c].data,
h,e),k,this)}else h=new Image,P(h,"error",x(this.Pa,this,b[c].data)),P(h,"load",x(this.oa,this,b[c].data,h,h.src));this.g++;h.src=f}this.S=a.data.after;this.S||(this.o=i);this.g--;zc(this)};r.Ta=function(){this.g--;zc(this);alert("Panoptikos cannot retrieve data from Reddit because Reddit is slow or you are not connected to the Internet.")};r.Qa=function(){this.g--;zc(this)};r.Ra=function(a,b,c){this.oa(a,b,c)};r.Pa=function(){this.g--;zc(this)};
r.oa=function(a,b,c){81===b.height&&161===b.width&&/^https?:\/\/i\.imgur\.com\//.test(b.src)?(this.ra.log(ec,"Ignoring Imgur\u2019s \u201cImage does not exist\u201d image: "+b.src,g),this.g--):(a=(new Wb(a,b,c)).G(),this.A.push(a),yc(this,a),this.g--,this.Q=i);zc(this)};function yc(a,b){for(var c,d=c=j,f=0,e=a.k.length;f<e;f++)c===j?(c=a.k[f],d=f):c>a.k[f]&&(c=a.k[f],d=f);c=d;c===j||(!a.n||!a.n[c])||(a.n[c].appendChild(b),a.k[c]=a.n[c].offsetHeight)}
r.Xa=function(){this.D=this.N=0;this.n=[];this.k=[];this.A=[];this.S="";this.g=0;this.ca();this.wa()};function zc(a){a.dispatchEvent(new Ac(Bc,a,a.g,a.Q,a.o))}var Bc="a";function Ac(a,b,c,d,f){K.call(this,a,b);this.tb=d;this.Ya=f;this.kb=c}y(Ac,K);function Cc(){var a;a=location.hash.replace(/^#/,"").split("+");for(var b=0,c=a.length;b<c;b++)"string"===typeof a[b]&&/^[0-9a-zA-Z_]+$/.test(a[b])||(a.splice(b,1),c--);a.length||(a=jc.slice());S=a;a=(new Db).G();document.body.appendChild(a);P(a,"click",this.gb,k,this);this.m=new xc(328,10,25);document.body.appendChild(this.m.z);this.m.ca();this.q=new tb;P(this.m,Bc,this.q.nb,k,this.q);P(this.q,ub,this.m.wa,k,this.m);a=this.q.G();document.body.appendChild(a);this.q.dispatchEvent(ub);P(window,"scroll",
this.Da,k,this)}var Dc=["p"],$=t;!(Dc[0]in $)&&$.execScript&&$.execScript("var "+Dc[0]);for(var Ec;Dc.length&&(Ec=Dc.shift());)!Dc.length&&Cc!==g?$[Ec]=Cc:$=$[Ec]?$[Ec]:$[Ec]={};Cc.prototype.Da=function(){window.scrollY+window.innerHeight+500>=document.body.scrollHeight&&this.q.dispatchEvent(ub)};Cc.prototype.gb=function(a){a.preventDefault();a=new xb;P(a,Bb,this.m.Xa,k,this.m);a.open()};
