application: panoptikos3
version: 2013-11-16-0
runtime: go
api_version: go1

# Set default expiration for static files to 7 days
default_expiration: 7d

handlers:
# Allow access to development CSS files locally.
# Development CSS files are not uploaded. See skip_files below.
- url: /dev-css/
  static_dir: webroot/dev-css/
  expiration: 0s

# Allow access to development JavaScript files locally.
# Development JavaScript files are not uploaded. See skip_files below.
- url: /dev-js/
  static_dir: webroot/dev-js/
  expiration: 0s

# Allow access to development HTML template files locally.
# Development HTML template files are not uploaded. See skip_files below.
- url: /dev-partials/
  static_dir: webroot/dev-partials/
  expiration: 0s

- url: /(.*\.css)
  static_files: webroot/compiled-css/\1
  upload: webroot/compiled-css/.*\.css

- url: /(.*\.js)
  static_files: webroot/compiled-js/\1
  upload: webroot/compiled-js/.*\.js

- url: /(.*\.html)
  static_files: webroot/compiled-partials/\1
  upload: webroot/compiled-partials/.*\.html

# File doesn't exist but some browsers request it, so serve an equivalent one.
- url: /apple-touch-icon-precomposed\.png
  static_files: webroot/images/apple-touch-icon-iphone-2x.png
  upload: webroot/images/apple-touch-icon-iphone-2x\.png

# File doesn't exist but some browsers request it, so serve an equivalent one.
- url: /favicon\.ico
  static_files: webroot/images/favicon-16.ico
  upload: webroot/images/favicon-16\.ico

- url: /(.*\.(?:gif|ico|jpg|png))
  static_files: webroot/images/\1
  upload: webroot/images/.*\.(?:gif|ico|jpg|png)

- url: /robots\.txt
  static_files: webroot/robots.txt
  upload: webroot/robots\.txt
  expiration: 1d

# Serve development index.html
- url: /.*
  static_files: webroot/dev-partials/index.html
  upload: webroot/dev-partials/index\.html

# Serve production index.html
# - url: /.*
#   static_files: webroot/compiled-partials/index.html
#   upload: webroot/compiled-partials/index\.html

# Files to skip when uploading the app to Google App Engine
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?webroot/dev-css
- ^(.*/)?webroot/dev-js
- ^(.*/)?webroot/dev-partials
