application: panoptikos3
version: 2013-05-15-0
runtime: go
api_version: go1

# Default expiration for static files
default_expiration: 7d

handlers:
- url: /(.*\.css)
  static_files: webroot/compiled-css/\1
  upload: webroot/compiled-css/.*\.css

- url: /dev-js/
  static_dir: webroot/dev-js/
  expiration: 0s

- url: /(.*\.js)
  static_files: webroot/compiled-js/\1
  upload: webroot/compiled-js/.*\.js

# Special case: File doesn't exist but some browsers request it.
- url: /apple-touch-icon-precomposed\.png
  static_files: webroot/images/apple-touch-icon-iphone-2x.png
  upload: webroot/images/apple-touch-icon-iphone-2x\.png

# Special case: File doesn't exist but some browsers request it.
- url: /favicon\.ico
  static_files: webroot/images/favicon-16.ico
  upload: webroot/images/favicon-16\.ico

- url: /(.*\.(?:gif|ico|jpg|png))
  static_files: webroot/images/\1
  upload: webroot/images/.*\.(?:gif|ico|jpg|png)

- url: /robots\.txt
  static_files: webroot/robots.txt
  upload: webroot/robots\.txt
  expiration: 1h

- url: /.*
  script: _go_app

inbound_services:
- warmup

# Files to skip when uploading the app to Google App Engine
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?libraries/closure-library-20120710-r2029
- ^(.*/)?webroot/dev-css
- ^(.*/)?webroot/dev-js
