application: panoptikos3
version: 2014-02-28-0
runtime: go
api_version: go1

# Set default expiration for static files to 7 days
default_expiration: "7d"

handlers:
# Allow access to development CSS and JS files locally.
# Development CSS and JS files are not uploaded. See skip_files below.
- url: /(.*\.(?:css|js))
  static_files: webroot/\1
  upload: webroot/(.*\.(?:css|js))
  expiration: "0s"

# Allow access to development HTML template files locally.
# Development HTML template files are not uploaded. See skip_files below.
- url: /dev-partials/.*\.html
  script: _go_app

# File doesn't exist but some browsers request it, so serve an equivalent one.
- url: /apple-touch-icon-precomposed\.png
  static_files: webroot/images/a4.png
  upload: webroot/images/a4\.png

# File doesn't exist but some browsers request it, so serve an equivalent one.
- url: /favicon\.ico
  static_files: webroot/images/f1.ico
  upload: webroot/images/f1\.ico

- url: /(.*\.(?:ico|png))
  static_files: webroot/images/\1
  upload: webroot/images/.*\.(?:ico|png)

- url: /robots\.txt
  static_files: webroot/robots.txt
  upload: webroot/robots\.txt
  expiration: "1d"

- url: /api/1/.*
  script: _go_app

- url: /worker/.*
  login: admin
  script: _go_app

# Handle requests to legacy URLs
- url: /(feeds|pictures|preferences|referrals|sources)(/.*)?
  script: _go_app

# Serve development index.html
- url: /.*
  static_files: webroot/dev-partials/index.html
  upload: webroot/dev-partials/index\.html
  expiration: "0s"

# # Serve production index.html
# - url: /.*
#   static_files: webroot/compiled-partials/index-1wgqTR.html
#   upload: webroot/compiled-partials/index-1wgqTR\.html
#   expiration: "1h"

# Files to skip when uploading the app to Google App Engine
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?webroot/components
- ^(.*/)?webroot/dev-css
- ^(.*/)?webroot/dev-js
- ^(.*/)?webroot/dev-partials
