var h=void 0,i=!0,j=null,l=!1,p,r=this;function aa(a){for(var a=a.split("."),b=r,c;c=a.shift();)if(b[c]!=j)b=b[c];else return j;return b}function s(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return"array"==ba(a)}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function da(a){return"function"==ba(a)}function ea(a){var b=typeof a;return"object"==b&&a!=j||"function"==b}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ha=0;
function ia(a,b,c){return a.call.apply(a.bind,arguments)}function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return v.apply(j,arguments)}var ka=Date.now||function(){return+new Date};
function w(a,b){function c(){}c.prototype=b.prototype;a.hb=b.prototype;a.prototype=new c};function la(a,b){for(var c=1;c<arguments.length;c++)var d=String(arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,d);return a}function x(a){if(!ma.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(na,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(oa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(pa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(qa,"&quot;"));return a}var na=/&/g,oa=/</g,pa=/>/g,qa=/\"/g,ma=/[&<>\"]/;var y,ra,sa,ta;function ua(){return r.navigator?r.navigator.userAgent:j}ta=sa=ra=y=l;var va;if(va=ua()){var wa=r.navigator;y=0==va.indexOf("Opera");ra=!y&&-1!=va.indexOf("MSIE");sa=!y&&-1!=va.indexOf("WebKit");ta=!y&&!sa&&"Gecko"==wa.product}var xa=y,z=ra,A=ta,B=sa,ya=r.navigator,za=-1!=(ya&&ya.platform||"").indexOf("Mac"),Aa;
a:{var Ba="",C;if(xa&&r.opera)var Ca=r.opera.version,Ba="function"==typeof Ca?Ca():Ca;else if(A?C=/rv\:([^\);]+)(\)|;)/:z?C=/MSIE\s+([^\);]+)(\)|;)/:B&&(C=/WebKit\/(\S+)/),C)var Da=C.exec(ua()),Ba=Da?Da[1]:"";if(z){var Ea,Fa=r.document;Ea=Fa?Fa.documentMode:h;if(Ea>parseFloat(Ba)){Aa=String(Ea);break a}}Aa=Ba}var Ga={};
function E(a){var b;if(!(b=Ga[a])){b=0;for(var c=String(Aa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",k=d[e]||"",q=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var o=q.exec(g)||["","",""],m=n.exec(k)||["","",""];if(0==o[0].length&&0==m[0].length)break;b=((0==o[1].length?0:parseInt(o[1],10))<(0==m[1].length?0:parseInt(m[1],10))?-1:(0==o[1].length?0:parseInt(o[1],
10))>(0==m[1].length?0:parseInt(m[1],10))?1:0)||((0==o[2].length)<(0==m[2].length)?-1:(0==o[2].length)>(0==m[2].length)?1:0)||(o[2]<m[2]?-1:o[2]>m[2]?1:0)}while(0==b)}b=Ga[a]=0<=b}return b}var Ha={};function Ia(){return Ha[9]||(Ha[9]=z&&!!document.documentMode&&9<=document.documentMode)};function Ja(){}var Ka=0;p=Ja.prototype;p.key=0;p.s=l;p.da=l;p.N=function(a,b,c,d,f,e){if(da(a))this.na=i;else if(a&&a.handleEvent&&da(a.handleEvent))this.na=l;else throw Error("Invalid listener argument");this.D=a;this.sa=b;this.src=c;this.type=d;this.capture=!!f;this.W=e;this.da=l;this.key=++Ka;this.s=l};p.handleEvent=function(a){return this.na?this.D.call(this.W||this.src,a):this.D.handleEvent.call(this.D,a)};function La(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ma(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}var Na="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Oa(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<Na.length;e++)c=Na[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};!z||Ia();var Pa=!z||Ia(),Qa=z&&!E("8");!B||E("528");A&&E("1.9b")||z&&E("8")||xa&&E("9.5")||B&&E("528");A&&!E("8")||z&&E("9");function F(a){Error.captureStackTrace?Error.captureStackTrace(this,F):this.stack=Error().stack||"";a&&(this.message=String(a))}w(F,Error);F.prototype.name="CustomError";function Ra(a,b){b.unshift(a);F.call(this,la.apply(j,b));b.shift();this.tb=a}w(Ra,F);Ra.prototype.name="AssertionError";function Sa(a,b){throw new Ra("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var G=Array.prototype,H=G.indexOf?function(a,b,c){return G.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ta=G.forEach?function(a,b,c){G.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},Ua=G.filter?function(a,b,c){return G.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,g=u(a)?a.split(""):
a,k=0;k<d;k++)if(k in g){var q=g[k];b.call(c,q,k,a)&&(f[e++]=q)}return f},Va=G.some?function(a,b,c){return G.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=u(a)?a.split(""):a,e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return i;return l};function Wa(a,b){var c=H(a,b);0<=c&&G.splice.call(a,c,1)}function Xa(a){return G.concat.apply(G,arguments)}function Ya(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Za(a,b,c){return 2>=arguments.length?G.slice.call(a,b):G.slice.call(a,b,c)};function $a(){this.Ga=l};function I(a,b){this.type=a;this.currentTarget=this.target=b}I.prototype.r=l;I.prototype.defaultPrevented=l;I.prototype.R=i;I.prototype.preventDefault=function(){this.defaultPrevented=i;this.R=l};function ab(a){ab[" "](a);return a}ab[" "]=s;function J(a,b){a&&this.N(a,b)}w(J,I);p=J.prototype;p.target=j;p.relatedTarget=j;p.offsetX=0;p.offsetY=0;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.button=0;p.keyCode=0;p.charCode=0;p.ctrlKey=l;p.altKey=l;p.shiftKey=l;p.metaKey=l;p.bb=l;p.ha=j;
p.N=function(a,b){var c=this.type=a.type;I.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(A){var f;a:{try{ab(d.nodeName);f=i;break a}catch(e){}f=l}f||(d=j)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=B||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=B||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.bb=za?a.metaKey:a.ctrlKey;this.state=a.state;this.ha=a;a.defaultPrevented&&this.preventDefault();delete this.r};
p.preventDefault=function(){J.hb.preventDefault.call(this);var a=this.ha;if(a.preventDefault)a.preventDefault();else if(a.returnValue=l,Qa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var K={},L={},M={},N={};
function O(a,b,c,d,f){if(b)if(t(b))for(var e=0;e<b.length;e++)O(a,b[e],c,d,f);else{var d=!!d,g=L;b in g||(g[b]={a:0,f:0});g=g[b];d in g||(g[d]={a:0,f:0},g.a++);var g=g[d],k=fa(a),q;g.f++;if(g[k]){q=g[k];for(e=0;e<q.length;e++)if(g=q[e],g.D==c&&g.W==f){if(g.s)break;return}}else q=g[k]=[],g.a++;var n=bb,o=Pa?function(a){return n.call(o.src,o.key,a)}:function(a){a=n.call(o.src,o.key,a);if(!a)return a},e=o;e.src=a;g=new Ja;g.N(c,e,a,b,d,f);c=g.key;e.key=c;q.push(g);K[c]=g;M[k]||(M[k]=[]);M[k].push(g);
a.addEventListener?(a==r||!a.ga)&&a.addEventListener(b,e,d):a.attachEvent(b in N?N[b]:N[b]="on"+b,e)}else throw Error("Invalid event type");}function cb(a,b,c,d,f){if(t(b))for(var e=0;e<b.length;e++)cb(a,b[e],c,d,f);else{d=!!d;a:{e=L;if(b in e&&(e=e[b],d in e&&(e=e[d],a=fa(a),e[a]))){a=e[a];break a}a=j}if(a)for(e=0;e<a.length;e++)if(a[e].D==c&&a[e].capture==d&&a[e].W==f){db(a[e].key);break}}}
function db(a){if(K[a]){var b=K[a];if(!b.s){var c=b.src,d=b.type,f=b.sa,e=b.capture;c.removeEventListener?(c==r||!c.ga)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in N?N[d]:N[d]="on"+d,f);c=fa(c);M[c]&&(f=M[c],Wa(f,b),0==f.length&&delete M[c]);b.s=i;if(b=L[d][e][c])b.pa=i,eb(d,e,c,b);delete K[a]}}}
function eb(a,b,c,d){if(!d.O&&d.pa){for(var f=0,e=0;f<d.length;f++)d[f].s?d[f].sa.src=j:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.pa=l;0==e&&(delete L[a][b][c],L[a][b].a--,0==L[a][b].a&&(delete L[a][b],L[a].a--),0==L[a].a&&delete L[a])}}function P(a,b,c,d,f){var e=1,b=fa(b);if(a[b]){a.f--;a=a[b];a.O?a.O++:a.O=1;try{for(var g=a.length,k=0;k<g;k++){var q=a[k];q&&!q.s&&(e&=fb(q,f)!==l)}}finally{a.O--,eb(c,d,b,a)}}return Boolean(e)}function fb(a,b){a.da&&db(a.key);return a.handleEvent(b)}
function bb(a,b){if(!K[a])return i;var c=K[a],d=c.type,f=L;if(!(d in f))return i;var f=f[d],e,g;if(!Pa){e=b||aa("window.event");var k=i in f,q=l in f;if(k){if(0>e.keyCode||e.returnValue!=h)return i;a:{var n=l;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(o){n=i}if(n||e.returnValue==h)e.returnValue=i}}n=new J;n.N(e,this);e=i;try{if(k){for(var m=[],$=n.currentTarget;$;$=$.parentNode)m.push($);g=f[i];g.f=g.a;for(var D=m.length-1;!n.r&&0<=D&&g.f;D--)n.currentTarget=m[D],e&=P(g,m[D],d,i,n);if(q){g=f[l];
g.f=g.a;for(D=0;!n.r&&D<m.length&&g.f;D++)n.currentTarget=m[D],e&=P(g,m[D],d,l,n)}}else e=fb(c,n)}finally{m&&(m.length=0)}return e}d=new J(b,this);return e=fb(c,d)};function gb(a){a=a.className;return u(a)&&a.match(/\S+/g)||[]}function hb(a,b){var c=gb(a),d=Za(arguments,1),f=c.length+d.length;ib(c,d);a.className=c.join(" ");return c.length==f}function ib(a,b){for(var c=0;c<b.length;c++)0<=H(a,b[c])||a.push(b[c])}function jb(a,b,c){var d=gb(a);u(b)?Wa(d,b):t(b)&&(d=Ua(d,function(a){return!(0<=H(b,a))}));u(c)&&!(0<=H(d,c))?d.push(c):t(c)&&ib(d,c);a.className=d.join(" ")};var kb=!z||Ia();!A&&!z||z&&Ia()||A&&E("1.9.1");z&&E("9");var lb=z||xa||B;function mb(a,b){function c(b,c){"style"==c?a.style.cssText=b:"class"==c?a.className=b:"for"==c?a.htmlFor=b:c in nb?a.setAttribute(nb[c],b):0==c.lastIndexOf("aria-",0)||0==c.lastIndexOf("data-",0)?a.setAttribute(c,b):a[c]=b}for(var d in b)c.call(h,b[d],d)}var nb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Q(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!kb&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',x(g.name),'"');if(g.type){e.push(' type="',x(g.type),'"');var k={};Oa(k,g);g=k;delete g.type}e.push(">");e=e.join("")}e=f.createElement(e);g&&(u(g)?e.className=g:t(g)?hb.apply(j,[e].concat(g)):mb(e,g));if(2<d.length)for(var q=f,n=e,f=function(a){a&&n.appendChild(u(a)?q.createTextNode(a):a)},g=2;g<d.length;g++)if(k=d[g],ca(k)&&!(ea(k)&&0<k.nodeType)){var o=Ta,m;a:{if((m=k)&&"number"==
typeof m.length){if(ea(m)){m="function"==typeof m.item||"string"==typeof m.item;break a}if(da(m)){m="function"==typeof m.item;break a}}m=l}o(m?Ya(k):k,f)}else f(k);return e}function ob(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function pb(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else ob(a),a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(b))};function qb(){this.Ga=l}w(qb,$a);p=qb.prototype;p.ga=i;p.ra=j;p.addEventListener=function(a,b,c,d){O(this,a,b,c,d)};p.removeEventListener=function(a,b,c,d){cb(this,a,b,c,d)};
p.dispatchEvent=function(a){var b=a.type||a,c=L;if(b in c){if(u(a))a=new I(a,this);else if(a instanceof I)a.target=a.target||this;else{var d=a,a=new I(b,this);Oa(a,d)}var d=1,f,c=c[b],b=i in c,e;if(b){f=[];for(e=this;e;e=e.ra)f.push(e);e=c[i];e.f=e.a;for(var g=f.length-1;!a.r&&0<=g&&e.f;g--)a.currentTarget=f[g],d&=P(e,f[g],a.type,i,a)&&a.R!=l}if(l in c)if(e=c[l],e.f=e.a,b)for(g=0;!a.r&&g<f.length&&e.f;g++)a.currentTarget=f[g],d&=P(e,f[g],a.type,l,a)&&a.R!=l;else for(f=this;!a.r&&f&&e.f;f=f.ra)a.currentTarget=
f,d&=P(e,f,a.type,l,a)&&a.R!=l;a=Boolean(d)}else a=i;return a};function rb(){this.Xa="Load images";this.Ya="Load more";this.Z="Loading images\u2026";this.M=l}w(rb,qb);rb.prototype.toElement=function(){var a=Q("div",{id:"board-controls"}),b=Q("button",j,this.Z);O(b,"click",this.Pa,l,this);this.F=b;a.appendChild(this.F);return a};rb.prototype.Pa=function(){pb(this.F,this.Z);this.dispatchEvent(sb)};rb.prototype.ib=function(a){0<a.fb?pb(this.F,this.Z):this.M?pb(this.F,this.Ya):pb(this.F,this.Xa)};var sb="a";function tb(a,b){I.call(this,a,b)}w(tb,I);function ub(a,b){var c=document.body.scrollHeight;if(c==h)throw Error("missing height argument");a.style.width=vb(b);a.style.height=vb(c)}function vb(a){"number"==typeof a&&(a=Math.round(a)+"px");return a};function wb(){}w(wb,qb);p=wb.prototype;
p.open=function(){if(!this.l){R=S();this.qa=S();var a=Q("div",{id:"subreddit-picker-background"});ub(a,document.body.scrollWidth);O(a,"click",this.Ja,l,this);var b=Q("div",{id:"subreddit-picker",style:{top:document.body.scrollHeight+10}});a.appendChild(b);var c=Q("input",{id:"subreddit-picker-text-field",placeholder:"Enter subreddit and press return",type:"text"});O(c,"keydown",this.Ua,l,this);b.appendChild(c);for(var c=Q("ul",{id:"subreddit-picker-subreddit-list"}),d=S(),f=0,e=d.length;f<e;f++){var g=
xb(d[f]);c.appendChild(g)}O(c,"click",this.Sa,l,this);this.xa=c;b.appendChild(this.xa);this.l=a;document.body.appendChild(this.l);O(window,"resize",this.L,l,this);this.dispatchEvent(yb)}};p.close=function(){this.l&&(cb(window,"resize",this.L,l,this),hb(this.l,"fade-out"),r.setTimeout(v(function(){var a=this.l;a&&a.parentNode&&a.parentNode.removeChild(a);this.qa=this.l=j},this),300),this.dispatchEvent(zb))};
p.Ja=function(a){if("subreddit-picker-background"===a.target.getAttribute("id")){this.close();a:{var a=S(),b=this.qa,c=a.length;if(c!==b.length)a=i;else{for(var d=0;d<c;d++)if(0>b.indexOf(a[d])){a=i;break a}a=l}}a&&this.dispatchEvent(Ab)}};
p.Sa=function(a){if(a.target.hasAttribute("data-subreddit-name")){var b=a.target.getAttribute("data-subreddit-name"),c=gb(a.target);0<=H(c,"subreddit-picker-subreddit-add-button")?(jb(a.target,"subreddit-picker-subreddit-add-button","subreddit-picker-subreddit-remove-button"),Bb(b)):(jb(a.target,"subreddit-picker-subreddit-remove-button","subreddit-picker-subreddit-add-button"),a=S(l),b=a.indexOf(b),0>b||(a.splice(b,1),R=a,location.hash=S(l).join("+")))}};
function xb(a){var b=Q("li","subreddit-picker-subreddit-list-item"),c=Q("button",{"class":"subreddit-picker-subreddit-remove-button","data-subreddit-name":a});pb(c,a);b.appendChild(c);return b}p.L=function(){this.l&&ub(this.l,document.body.offsetWidth)};p.Ua=function(a){if("enter"===a.key){var b=xb(a.target.value);this.xa.appendChild(b);Bb(a.target.value);a.target.value=""}};var zb="a",yb="b",Ab="c";function Cb(){}Cb.prototype.toElement=function(){var a=Q("button",{id:"subreddit-picker-launcher"},"Edit Subreddits");O(a,"click",this.La,l,this);return a};Cb.prototype.La=function(a){a.preventDefault();(new wb).open()};var Db=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Eb(a){if("function"==typeof a.i)return a.i();if(u(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return La(a)};function Fb(a,b){this.j={};this.c=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Fb?(c=a.q(),d=a.i()):(c=Ma(a),d=La(a));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}p=Fb.prototype;p.a=0;p.za=0;p.i=function(){Gb(this);for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};p.q=function(){Gb(this);return this.c.concat()};p.z=function(a){return T(this.j,a)};
p.remove=function(a){return T(this.j,a)?(delete this.j[a],this.a--,this.za++,this.c.length>2*this.a&&Gb(this),i):l};function Gb(a){if(a.a!=a.c.length){for(var b=0,c=0;b<a.c.length;){var d=a.c[b];T(a.j,d)&&(a.c[c++]=d);b++}a.c.length=c}if(a.a!=a.c.length){for(var f={},c=b=0;b<a.c.length;)d=a.c[b],T(f,d)||(a.c[c++]=d,f[d]=1),b++;a.c.length=c}}p.get=function(a,b){return T(this.j,a)?this.j[a]:b};p.set=function(a,b){T(this.j,a)||(this.a++,this.c.push(a),this.za++);this.j[a]=b};p.w=function(){return new Fb(this)};
function T(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Hb(a,b){var c;if(a instanceof Hb)this.e=b!==h?b:a.e,Ib(this,a.t),c=a.T,U(this),this.T=c,c=a.A,U(this),this.A=c,Jb(this,a.Q),c=a.P,U(this),this.P=c,Kb(this,a.h.w()),c=a.K,U(this),this.K=c;else if(a&&(c=String(a).match(Db))){this.e=!!b;Ib(this,c[1]||"",i);var d=c[2]||"";U(this);this.T=d?decodeURIComponent(d):"";d=c[3]||"";U(this);this.A=d?decodeURIComponent(d):"";Jb(this,c[4]);d=c[5]||"";U(this);this.P=d?decodeURIComponent(d):"";Kb(this,c[6]||"",i);c=c[7]||"";U(this);this.K=c?decodeURIComponent(c):
""}else this.e=!!b,this.h=new Lb(j,0,this.e)}p=Hb.prototype;p.t="";p.T="";p.A="";p.Q=j;p.P="";p.K="";p.Wa=l;p.e=l;p.toString=function(){var a=[],b=this.t;b&&a.push(Mb(b,Nb),":");if(b=this.A){a.push("//");var c=this.T;c&&a.push(Mb(c,Nb),"@");a.push(encodeURIComponent(String(b)));b=this.Q;b!=j&&a.push(":",String(b))}if(b=this.P)this.A&&"/"!=b.charAt(0)&&a.push("/"),a.push(Mb(b,"/"==b.charAt(0)?Ob:Pb));(b=this.h.toString())&&a.push("?",b);(b=this.K)&&a.push("#",Mb(b,Qb));return a.join("")};p.w=function(){return new Hb(this)};
function Ib(a,b,c){U(a);a.t=c?b?decodeURIComponent(b):"":b;a.t&&(a.t=a.t.replace(/:$/,""))}function Jb(a,b){U(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.Q=b}else a.Q=j}function Kb(a,b,c){U(a);b instanceof Lb?(a.h=b,a.h.ba(a.e)):(c||(b=Mb(b,Rb)),a.h=new Lb(b,0,a.e))}function Sb(a,b,c){U(a);t(c)||(c=[String(c)]);Tb(a.h,b,c)}function U(a){if(a.Wa)throw Error("Tried to modify a read-only Uri");}p.ba=function(a){this.e=a;this.h&&this.h.ba(a);return this};
function Mb(a,b){return u(a)?encodeURI(a).replace(b,Ub):j}function Ub(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Nb=/[#\/\?@]/g,Pb=/[\#\?:]/g,Ob=/[\#\?]/g,Rb=/[\#\?@]/g,Qb=/#/g;function Lb(a,b,c){this.d=a||j;this.e=!!c}
function V(a){if(!a.b&&(a.b=new Fb,a.a=0,a.d))for(var b=a.d.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),f=j,e=j;0<=d?(f=b[c].substring(0,d),e=b[c].substring(d+1)):f=b[c];f=decodeURIComponent(f.replace(/\+/g," "));f=W(a,f);a.add(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}p=Lb.prototype;p.b=j;p.a=j;p.add=function(a,b){V(this);this.d=j;var a=W(this,a),c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.a++;return this};
p.remove=function(a){V(this);a=W(this,a);return this.b.z(a)?(this.d=j,this.a-=this.b.get(a).length,this.b.remove(a)):l};p.z=function(a){V(this);a=W(this,a);return this.b.z(a)};p.q=function(){V(this);for(var a=this.b.i(),b=this.b.q(),c=[],d=0;d<b.length;d++)for(var f=a[d],e=0;e<f.length;e++)c.push(b[d]);return c};p.i=function(a){V(this);var b=[];if(a)this.z(a)&&(b=Xa(b,this.b.get(W(this,a))));else for(var a=this.b.i(),c=0;c<a.length;c++)b=Xa(b,a[c]);return b};
p.set=function(a,b){V(this);this.d=j;a=W(this,a);this.z(a)&&(this.a-=this.b.get(a).length);this.b.set(a,[b]);this.a++;return this};p.get=function(a,b){var c=a?this.i(a):[];return 0<c.length?String(c[0]):b};function Tb(a,b,c){a.remove(b);0<c.length&&(a.d=j,a.b.set(W(a,b),Ya(c)),a.a+=c.length)}
p.toString=function(){if(this.d)return this.d;if(!this.b)return"";for(var a=[],b=this.b.q(),c=0;c<b.length;c++)for(var d=b[c],f=encodeURIComponent(String(d)),d=this.i(d),e=0;e<d.length;e++){var g=f;""!==d[e]&&(g+="="+encodeURIComponent(String(d[e])));a.push(g)}return this.d=a.join("&")};p.w=function(){var a=new Lb;a.d=this.d;this.b&&(a.b=this.b.w());return a};function W(a,b){var c=String(b);a.e&&(c=c.toLowerCase());return c}
p.ba=function(a){if(a&&!this.e){V(this);this.d=j;var b=this.b,c=function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),Tb(this,c,a))};if("function"==typeof b.forEach)b.forEach(c,this);else if(ca(b)||u(b))Ta(b,c,this);else{var d;if("function"==typeof b.q)d=b.q();else if("function"!=typeof b.i)if(ca(b)||u(b)){d=[];for(var f=b.length,e=0;e<f;e++)d.push(e)}else d=Ma(b);else d=h;b=Eb(b);f=b.length;for(e=0;e<f;e++)c.call(this,b[e],d&&d[e])}}this.e=a};function Vb(a,b,c){this.ka=c;this.X=b;this.ya=a}Vb.prototype.toElement=function(){var a=Q("div","board-item"),b=Q("a",{"class":"board-item-image-anchor",href:this.ka?this.ka:this.X.src}),c=Q("img",{"class":"board-item-image","data-original-src":this.X.src,src:this.X.src});b.appendChild(c);a.appendChild(b);b=Q("a",{"class":"board-item-title-anchor",href:"http://www.reddit.com"+this.ya.ub});b.innerHTML=this.ya.title;a.appendChild(b);return a};function Wb(a){return Xb(a||arguments.callee.caller,[])}
function Xb(a,b){var c=[];if(0<=H(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Yb(a)+"(");for(var d=a.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=String(e);break;case "boolean":e=e?"true":"false";break;case "function":e=(e=Yb(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}b.push(a);c.push(")\n");try{c.push(Xb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Yb(a){if(Zb[a])return Zb[a];a=String(a);if(!Zb[a]){var b=/function ([^\(]+)/.exec(a);Zb[a]=b?b[1]:"[Anonymous]"}return Zb[a]}var Zb={};function X(a,b,c,d,f){this.reset(a,b,c,d,f)}X.prototype.gb=0;X.prototype.ja=j;X.prototype.ia=j;var $b=0;X.prototype.reset=function(a,b,c,d,f){this.gb="number"==typeof f?f:$b++;this.vb=d||ka();this.C=a;this.$a=b;this.sb=c;delete this.ja;delete this.ia};X.prototype.va=function(a){this.C=a};function Y(a){this.ab=a}Y.prototype.n=j;Y.prototype.C=j;Y.prototype.U=j;Y.prototype.ma=j;function ac(a,b){this.name=a;this.value=b}ac.prototype.toString=function(){return this.name};var bc=new ac("INFO",800),cc=new ac("CONFIG",700),dc=new ac("FINE",500);p=Y.prototype;p.getParent=function(){return this.n};p.Ha=function(){this.U||(this.U={});return this.U};p.va=function(a){this.C=a};function ec(a){if(a.C)return a.C;if(a.n)return ec(a.n);Sa("Root logger has no level set.");return j}
p.log=function(a,b,c){if(a.value>=ec(this).value){a=this.Ia(a,b,c);b="log:"+a.$a;r.console&&(r.console.timeStamp?r.console.timeStamp(b):r.console.markTimeline&&r.console.markTimeline(b));r.msWriteProfilerMark&&r.msWriteProfilerMark(b);for(b=this;b;){var c=b,d=a;if(c.ma)for(var f=0,e=h;e=c.ma[f];f++)e(d);b=b.getParent()}}};
p.Ia=function(a,b,c){var d=new X(a,String(b),this.ab);if(c){d.ja=c;var f;var e=arguments.callee.caller;try{var g;var k=aa("window.location.href");if(u(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:k,stack:"Not available"};else{var q,n,o=l;try{q=c.lineNumber||c.rb||"Not available"}catch(m){q="Not available",o=i}try{n=c.fileName||c.filename||c.sourceURL||k}catch($){n="Not available",o=i}g=o||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:q,
fileName:n,stack:c.stack||"Not available"}:c}f="Message: "+x(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+x(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+x(Wb(e)+"-> ")}catch(D){f="Exception trying to expose exception! You win, we lose. "+D}d.ia=f}return d};p.info=function(a,b){this.log(bc,a,b)};var fc={},gc=j;
function hc(a){gc||(gc=new Y(""),fc[""]=gc,gc.va(cc));var b;if(!(b=fc[a])){b=new Y(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=hc(a.substr(0,c));c.Ha()[d]=b;b.n=c;fc[a]=b}return b};var ic="1000words agricultureporn aviation birdpics cityporn earthporn itookapicture picturechallenge wallpaper wallpapers windowshots".split(" ");function S(a){"boolean"!==typeof a&&(a=i);return 0===R.length&&a?ic.slice():R.slice()}function Bb(a){var b=S(l);0<=b.indexOf(a)||(b.push(a),R=b,location.hash=S(l).join("+"))}for(var R,jc=location.hash.replace(/^#/,"").split("+"),kc=0,lc=jc.length;kc<lc;kc++){var mc=jc[kc];"string"===typeof mc&&/^[0-9a-zA-Z_]+$/.test(mc)||(jc.splice(kc,1),lc--)}R=jc;
0===R.length&&(R=ic.slice());/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function nc(a,b){this.v=[];this.lb=a;this.Fa=b||j}p=nc.prototype;p.p=l;p.B=l;p.G=0;p.wa=l;p.Ca=l;p.Aa=0;p.fa=function(a,b){oc(this,a,b);this.G--;0==this.G&&this.p&&pc(this)};function oc(a,b,c){a.p=i;a.aa=c;a.B=!b;pc(a)}function qc(a){if(a.p){if(!a.wa)throw new rc(a);a.wa=l}}function sc(a){return Va(a.v,function(a){return da(a[1])})}
function pc(a){a.ca&&(a.p&&sc(a))&&(r.clearTimeout(a.ca),delete a.ca);a.n&&(a.n.Aa--,delete a.n);for(var b=a.aa,c=l,d=l;a.v.length&&0==a.G;){var f=a.v.shift(),e=f[0],g=f[1],f=f[2];if(e=a.B?g:e)try{var k=e.call(f||a.Fa,b);k!==h&&(a.B=a.B&&(k==b||k instanceof Error),a.aa=b=k);b instanceof nc&&(d=i,a.G++)}catch(q){b=q,a.B=i,sc(a)||(c=i)}}a.aa=b;d&&a.G&&(d=b,k=v(a.fa,a,i),e=v(a.fa,a,l),d.v.push([k,e,h]),d.p&&pc(d),b.Ca=i);c&&(a.ca=r.setTimeout(function(){throw new tc(b);},0))}
function rc(a){F.call(this);this.nb=a}w(rc,F);rc.prototype.message="Already called";function tc(a){F.call(this);this.mb=a;this.message="Unhandled Error in Deferred: "+(a.message||"[No message]")}w(tc,F);function uc(){if(this&&this.ua){var a=this.ua;a&&"SCRIPT"==a.tagName&&vc(a,i,this.H)}}function vc(a,b,c){c!=j&&r.clearTimeout(c);a.onload=s;a.onerror=s;a.onreadystatechange=s;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function wc(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);F.call(this,c);this.code=a}w(wc,F);function xc(a,b){this.jb=new Hb(a);this.Ba=b?b:"callback";this.H=5E3}var yc=0;
xc.prototype.send=function(a,b,c,d){var f=a||j,e=d||"_"+(yc++).toString(36)+ka().toString(36);r._callbacks_||(r._callbacks_={});a=this.jb.w();if(f)for(var g in f)(!f.hasOwnProperty||f.hasOwnProperty(g))&&Sb(a,g,f[g]);b&&(r._callbacks_[e]=function(a){zc(e,i);b.apply(h,arguments)},Sb(a,this.Ba,"_callbacks_."+e));var k=a.toString(),q={timeout:this.H,Da:i};g=q.document||document;var n=document.createElement("SCRIPT"),a={ua:n,H:h},o=new nc(uc,a),m=j,d=q.timeout!=j?q.timeout:5E3;0<d&&(m=window.setTimeout(function(){vc(n,
i);var a=new wc(1,"Timeout reached for loading script "+k);qc(o);oc(o,l,a)},d),a.H=m);n.onload=n.onreadystatechange=function(){if(!n.readyState||n.readyState=="loaded"||n.readyState=="complete"){vc(n,q.Da||l,m);qc(o);oc(o,i,j)}};n.onerror=function(){vc(n,i,m);var a=new wc(0,"Error while loading script "+k);qc(o);oc(o,l,a)};mb(n,{type:"text/javascript",charset:"UTF-8",src:k});a=g.getElementsByTagName("HEAD");(!a||0==a.length?g.documentElement:a[0]).appendChild(n);o.v.push([j,function(){zc(e,l);c&&
c(f)},h]);o.p&&pc(o);return{qb:e,ob:o}};function zc(a,b){r._callbacks_[a]&&(b?delete r._callbacks_[a]:r._callbacks_[a]=s)};function Ac(a,b,c,d){this.I=a;this.u=[];this.k=[];this.ea=c;this.Ea=b;this.m=[];this.M=l;this.Y="";this.oa=hc("panoptikos.ui.Board");this.Za=d;this.cb=3E4;this.g=0;O(window,"resize",this.L,l,this);O(this.I,"click",this.Ka,l,this);z&&(a=Q("link",{href:"css/board-item-ie.css",rel:"stylesheet",type:"text/css"}),document.head.appendChild(a))}w(Ac,qb);p=Ac.prototype;
p.Ka=function(a){a.preventDefault();if("board-item-title-anchor"===a.target.className&&a.target.hasAttribute("href"))window.open(a.target.getAttribute("href"));else{if("board-item-image"===a.target.className){var b;b=a.target;lb?b=b.parentElement:(b=b.parentNode,b=ea(b)&&1==b.nodeType?b:j);a.target=b}"board-item-image-anchor"===a.target.className&&a.target.hasAttribute("href")&&window.open(a.target.getAttribute("href"))}};p.L=function(){clearTimeout(this.eb);this.eb=r.setTimeout(v(this.$,this),10)};
p.$=function(){var a=this.I.offsetWidth,b=1,c=this.Ea;a<c?c=a:b+=Math.floor((a-c)/(c+this.ea));this.J!==c&&(this.J=c,a=".board-column {margin-left: "+this.ea+"px; width: "+this.J+"px;}",a+=".board-item {width: "+(this.J-8)+"px;}",this.S?this.S.innerHTML=a:(this.S=Q("style",{type:"text/css"}),this.S.innerHTML=a,document.head.appendChild(this.S)));if(b!==this.V){this.V=b;this.m=[];this.k=[];ob(this.I);for(b=0;b<this.V;b++)a=Q("div","board-column"),this.m.push(a),this.k.push(0),this.I.appendChild(a);
this.oa.info("Rebuilding board with "+this.u.length+" images.");b=0;for(a=this.u.length;b<a;b++)Bc(this,this.u[b])}};p.ta=function(){if(!(0<this.g)){this.g++;var a=new Hb("http://www.reddit.com/r/"+S().join("+")+".json"),b=this.Y;U(a);a.h.set("after",b);b=this.Za;U(a);a.h.set("limit",b);a=new xc(a,"jsonp");a.H=this.cb;a.send(j,v(this.Ra,this),v(this.Qa,this))}};
p.Ra=function(a){for(var b=a.data.children,c=0,d=b.length;c<d;c++){var f=b[c].data.url,e=b[c].data.url.match(/^https?:\/\/(?:i\.)?imgur\.com\/([a-zA-Z0-9]+)/);if(e){var f="http://i.imgur.com/"+e[1]+"l.jpg",e="http://i.imgur.com/"+e[1]+".jpg",g=new Image;O(g,"error",v(this.Na,this,[b[c].data]),l,this);O(g,"load",v(this.Oa,this,b[c].data,g,e),l,this)}else g=new Image,O(g,"error",v(this.Ma,this,b[c].data)),O(g,"load",v(this.la,this,b[c].data,g,g.src));this.g++;g.src=f}this.Y=a.data.kb;this.g--;Cc(this)};
p.Qa=function(){this.g--;Cc(this);alert("Panoptikos cannot retrieve data from Reddit because Reddit is slow or you are not connected to the Internet.")};p.Na=function(){this.g--;Cc(this)};p.Oa=function(a,b,c){this.la(a,b,c)};p.Ma=function(){this.g--;Cc(this)};
p.la=function(a,b,c){81===b.height&&161===b.width&&b.src.match(/^https?:\/\/i\.imgur\.com\//)?(this.oa.log(dc,"Ignoring Imgur\u2019s \u201cImage does not exist\u201d image: "+b.src,h),this.g--):(a=(new Vb(a,b,c)).toElement(),this.u.push(a),Bc(this,a),this.g--,this.M=i);Cc(this)};function Bc(a,b){for(var c,d=c=j,f=0,e=a.k.length;f<e;f++)c===j?(c=a.k[f],d=f):c>a.k[f]&&(c=a.k[f],d=f);c=d;c===j||(!a.m||!a.m[c])||(a.m[c].appendChild(b),a.k[c]=a.m[c].offsetHeight)}
p.Va=function(){this.J=this.V=j;this.m=[];this.k=[];this.u=[];this.Y="";this.g=0;this.$();this.ta()};function Cc(a){a.dispatchEvent(new Dc(Ec,a,a.g,a.M))}var Ec="a";function Dc(a,b,c,d){I.call(this,a,b);this.pb=d;this.fb=c}w(Dc,I);function Fc(){var a;a=u("board")?document.getElementById("board"):"board";var b=(new Cb).toElement();a.parentNode&&a.parentNode.insertBefore(b,a);O(b,"click",this.Ta,l,this);this.o=new Ac(a,328,10,25);this.o.$();a=new rb;O(this.o,Ec,a.ib,l,a);O(a,sb,this.o.ta,l,this.o);b=a.toElement();document.body.appendChild(b);a.dispatchEvent(new tb(sb))}var Gc=["panoptikos","Panoptikos"],Z=r;!(Gc[0]in Z)&&Z.execScript&&Z.execScript("var "+Gc[0]);
for(var Hc;Gc.length&&(Hc=Gc.shift());)!Gc.length&&Fc!==h?Z[Hc]=Fc:Z=Z[Hc]?Z[Hc]:Z[Hc]={};Fc.prototype.Ta=function(a){a.preventDefault();O(new wb,Ab,this.o.Va,l,this.o)};
